### PR TITLE
Check for `NULL` before calling `json_object_get_string()`

### LINKED ISSUE #2102: Segmentation fault (Core dumping) loading feeds after updating Nextcloud News to 18.1.0
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
```
Newsboat 2.27.0 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2022 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2022 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles:
- JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
- optional-lite library, licensed under the Boost Software License: https://github.com/martinmoene/optional-lite
- expected-lite library, licensed under the Boost Software License: https://github.com/martinmoene/expected-lite

Newsboat 2.27.0
System: Linux 5.18.3-arch1-1 (x86_64)
Compiler: g++ 11.2.0
ncurses: ncurses 6.3.20211021 (compiled with 6.3)
libcurl: libcurl/7.83.1 OpenSSL/1.1.1o zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.47.0 (compiled with 7.82.0)
SQLite: 3.38.5 (compiled with 3.38.1)
libxml2: compiled with 2.9.13

```
Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
browser qutebrowser
# Key Bindings
unbind-key j
bind-key J next-feed
unbind-key k
bind-key K prev-feed
unbind-key DOWN
bind-key j down
unbind-key UP
bind-key k up
unbind-key ENTER
bind-key l open
unbind-key q
bind-key h quit
unbind-key PPAGE
bind-key ^B pageup
unbind-key NPAGE
bind-key ^F pagedown
unbind-key g
bind-key s sort
unbind-key G
bind-key S rev-sort
unbind-key HOME
bind-key g home
unbind-key END
bind-key G end
unbind-key Q
bind-key q hard-quit
bind-key ^S save
bind-key ^U toggle-show-read-feeds

macro v set browser "mpv"; open-in-browser ; set browser "qutebrowser"
macro V set browser "ytdl-mpv"; open-in-browser; set browser "qutebrowser"
download-path "~/podcasts/%n"
download-filename-format "%t_%F.%e"
player "podcast_player"

include dracula
reload-threads 100
auto-reload yes

urls-source "ocnews"
ocnews-url "https://nextcloud.tansanchez.net"
ocnews-login "<redacted>"
ocnews-passwordeval "<redacted>"

```

Steps to reproduce the issue:

1. Update Nextcloud News to 18.1.0

2.Open Newsboat and refresh a feed with new articles

3.Application hangs and kills with a segmentation fault with this message
```
156028 segmentation fault (core dumped)
```

**Other info you think is relevant**:
The application was working fine this morning but stopped failing the moment I updated Nextcloud News to 18.1.0. 
I have tried in 2 different machines both with the same version of Newsboat and the same config. I have tried in my phone as well using the Nextcloud News mobile app and it works as expected. This application had an update a couple days ago where one of the items in the change log was to adapt for this specific version of Nextcloud News. My hunch is that there has been some changes made to the API that break Newsboat. I have my own instance of Nextcloud so if you need any logs, I can assist.

### PR DESCRIPTION
**Pull request by Minoru**
Fixes #2102, and prevents the same problem from happening to other APIs. Even if those other APIs never return `null`, it's better to be safe than sorry.

Since this is a fix for a segfault, I intend to merge this *before* the 2.28 release. Thus, reviews are especially welcome. @dennisschagt?

### CODE REVIEW

File: src/newsblurapi.cpp [hunk 1]
```diff
@@ -152,20 +163,20 @@ std::map<std::string, std::vector<std::string>> NewsBlurApi::mk_feeds_to_tags(
 			continue;
 		}
 
-		json_object_object_foreach(
-			tag_to_feed_ids, key, feeds_with_tag_obj) {
+		// invariant: `tag_to_feed_ids` in a JSON object
```
Comment (dennisschagt) [inline src/newsblurapi.cpp:166]:
```suggestion
		// invariant: `tag_to_feed_ids` is a JSON object
```

File: src/newsblurapi.cpp [hunk 2]
```diff
@@ -183,7 +194,8 @@ bool request_successfull(json_object* payload)
 	if (json_object_object_get_ex(payload, "result", &result) == FALSE) {
 		return false;
 	} else {
-		return !strcmp("ok", json_object_get_string(result));
+		const auto result_str = json_object_get_string(result);
+		return result_str != nullptr && !strcmp("ok", result_str);
```
Comment (dennisschagt) [inline src/newsblurapi.cpp:198]:
```suggestion
		return result_str != nullptr && strcmp("ok", result_str) == 0;
```

**Review by dennisschagt — APPROVED** [review]
LGTM

A few suggestions, but I would already be fine with merging as-is

File: src/feedhqapi.cpp [hunk 3]
```diff
@@ -130,16 +130,23 @@ std::vector<TaggedFeedUrl> FeedHqApi::get_subscribed_urls()
...
 
 		json_object* title_str{};
 		json_object_object_get_ex(sub, "title", &title_str);
 		const char* title = json_object_get_string(title_str);
+		if (title == nullptr) {
+			LOG(Level::DEBUG, "Skipping a subscription with id %s which doesn't have a title", id);
+			continue;
+		}
 
 		tags.push_back(std::string("~") + title);
```
[the remark this answers is not in the document]
Comment (Minoru) [reply src/feedhqapi.cpp]: Excellent catch! Done in https://github.com/newsboat/newsboat/pull/2105/commits/db3b033838517855fb94e04952327884ad635f68.

**Comment by Minoru** [comment]
Thanks for the very thorough review, @dennisschagt! I think the PR is much better now thanks to your comments.

**Review by dennisschagt — APPROVED** [review]
LGTM

**Comment by Minoru** [comment]
Thanks! I'll squash and merge it then.
