### PR TITLE
Make FeedContainer methods thread-safe

### LINKED ISSUE #1025: Segmentation fault (core dumped) after upgrading to v2.20
Only happens half of the time.

I tried running with an empty config, but it didn't solve it.

On the other hand deleting cache.db always works. So I think it is cache related.

```
Starting newsboat 2.20.0...
Loading configuration...done.
Opening cache...done.
Loading URLs from /home/polve/.config/newsboat/urls...done.
Loading articles from cache...done.
Segmentation fault (core dumped)
```

**`newsboat -v` output**:
newsboat 2.20.0
System: Linux 5.7.4-arch1-1 (x86_64)
Compiler: g++ 10.1.0
ncurses: ncurses 6.2.20200212 (compiled with 6.2)
libcurl: libcurl/7.70.0 OpenSSL/1.1.1g zlib/1.2.11 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh2/1.9.0 nghttp2/1.41.0 (compiled with 7.70.0)
SQLite: 3.32.3 (compiled with 3.32.3)
libxml2: compiled with 2.9.10

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
# vim: set filetype:conf

auto-reload yes
feed-sort-order lastupdated
reload-threads 4
show-read-feeds no
max-items 30

external-url-viewer "urlscan -dc -r 'linkhandler {}'"

bind-key  j  down
bind-key  k  up
bind-key  j  next                    articlelist
bind-key  k  prev                    articlelist
bind-key  J  next-feed               articlelist
bind-key  K  prev-feed               articlelist
bind-key  G  end
bind-key  g  home
bind-key  d  pagedown
bind-key  u  pageup
bind-key  l  open
bind-key  h  quit
bind-key  a  toggle-article-read
bind-key  n  next-unread
bind-key  N  prev-unread
bind-key  D  pb-download
bind-key  U  show-urls
bind-key  x  pb-delete
bind-key  L  toggle-show-read-feeds

color  listnormal         green    default  bold
color  listfocus          yellow   black    standout  bold
color  listnormal_unread  cyan     default
color  listfocus_unread   yellow   black    standout  bold
color  info               black    yellow   standout

browser linkhandler
macro , open-in-browser
macro k open-in-browser-and-mark-read ; hard-quit
macro t set browser "tsp youtube-dl --add-metadata -ic" ; open-in-browser ; set browser linkhandler
macro a set browser "tsp youtube-dl --add-metadata -xic -f bestaudio/best" ; open-in-browser ; set browser linkhandler
macro v set browser "setsid mpv" ; open-in-browser ; set browser linkhandler
macro w set browser "lynx" ; open-in-browser ; set browser linkhandler
macro c set browser "xsel -b <<<" ; open-in-browser ; set browser linkhandler

highlight all "---.*---" yellow
highlight feedlist ".*(0/0))" black
highlight article "(^Feed:.*|^Title:.*|^Author:.*)" cyan default bold
highlight article "(^Link:.*|^Date:.*)" default default
highlight article "https?://[^ ]+" green default
highlight article "^(Title):.*$" blue default bold
highlight article "\\[[0-9][0-9]*\\]" magenta default bold
highlight article "\\[image\\ [0-9]+\\]" green default bold
highlight article "\\[embedded flash: [0-9][0-9]*\\]" green default bold
highlight article ":.*\\(link\\)$" cyan default
highlight article ":.*\\(image\\)$" blue default bold
highlight article ":.*\\(embedded flash\\)$" magenta default
```

Steps to reproduce the issue:

1. run `newsboat`

**Other info**:

Only happens with 2.20, I tried reverting to 2.19 and it works as expected.

I installed it from the Arch official repo.

I have ~50 youtube channels in the urls file and ~20 other rss.

### PR DESCRIPTION
**Pull request by Minoru**
Fixes #1025.

Thanks to @dennisschagt for investigating that issue to a point where the problem was rather obvious.

Reviews are welcome! Asking for one from @dennisschagt, since he reproduced the original issue and should be able to easily double-check the fix.

Will merge for 2.20.1 tomorrow.

### CODE REVIEW

File: include/feedcontainer.h [hunk 1]
```diff
@@ -43,7 +43,7 @@ class FeedContainer {
 	std::vector<std::shared_ptr<RssFeed>> feeds;
```
Comment (dennisschagt) [inline include/feedcontainer.h:43]: This variable is still public so code outside of this class can still use/change the feeds vector without locking `FeedContainer::feeds_mutex`.

The only classes directly using this variable are the `opml` and `Controller` classes:
- `opml`: Probably is not an issue as it is only used for exporting (looks like this is always done before/without starting extra threads so should be save)
- `Controller`: I think the uses of `feedcontainer.feeds` might allow some race conditions. When accessing the `feeds` variable, it locks `Controller::feeds_mutex` but this is not the same mutex as the mutex used in the FeedContainer class.

**Comment by Minoru** [comment]
Thanks for the review! I want 2.20.1 release to be bugfix-only, so I'll move the comment to a new issue.

File: include/feedcontainer.h (hunk 1 above)
Comment (dennisschagt) [reply include/feedcontainer.h:43]: @Minoru: Thanks for opening the issue. That resolves this comment.
