### PR TITLE
Check if all attributes are valid before applying filter

### LINKED ISSUE #2857: List contains stale items after applied filter triggers a MatcherException
Newsboat version: 3762bc4f2a2d2aed67b9900e9c8d9c2f97a4475d (current master)

Config file:

```
define-filter "age < 1" "age < 1"
```

Steps to reproduce the issue:

1. In feedlist: Select defined filter (press `f`, select the filter and press ENTER)

2. Select a feed and open it (ENTER)

3. Notice that the feed is not opened. An error is shown instead: `No feed selected!`

**Other info you think is relevant**:
Git bisect points to fff505bf2e3e8fd8a6823a7883aaaee7ebf3547b (part of https://github.com/newsboat/newsboat/pull/974), although before that change there are already seem to be some issues when a broken filter is applied (e.g. when using `:<number>` to go to a specific feed location)

Found while looking into https://github.com/newsboat/newsboat/issues/2856 (which I'm not yet sure how to properly interpret/reproduce)

### PR DESCRIPTION
**Pull request by dennisschagt**
Resolves https://github.com/newsboat/newsboat/issues/2857
Obsoletes https://github.com/newsboat/newsboat/pull/2858

### CODE REVIEW

**Comment by Minoru** [comment]
I'll take a proper look tomorrow, but one question I have already is how this impacts the Rust post of filter parsing. Would it need updating? IIRC it only does parsing and evaluation, but it has to interface with `Matcher` too. (I'm not asking for that Rust code to be updated, I just want to know if it would need updating later.)

File: src/feedlistformaction.cpp [hunk 1]
```diff
@@ -1132,15 +1132,32 @@ void FeedListFormAction::apply_filter(const std::string& filtertext)
...
+
+		if (unavailable_attributes.empty()) {
+			matcher = new_matcher;
+			save_filterpos();
+			filter_active = true;
+			do_redraw = true;
+		} else {
+			v.get_statusline().show_error(strprintf::fmt(
+					_("Error: Some filter attributes not availabe in feedlist: %s"),
+					utils::join(unavailable_attributes, ",")));
```
Comment (dennisschagt) [inline src/feedlistformaction.cpp]: From Lyse on irc:
> Are the two new error messages missing an "are"?
> Also, not sure if joining the unavailable attributes with comma and space would make them more readable.

I think those are nice suggestions so I plan to take them along

**Review by dennisschagt — COMMENTED** [review]
> one question I have already is how this impacts the Rust post of filter parsing. Would it need updating? IIRC it only does parsing and evaluation, but it has to interface with Matcher too. (I'm not asking for that Rust code to be updated, I just want to know if it would need updating later.)

I think it does, but looks like it is quite straightforward to port this.
Untested, but I expect something like this would suffice:
```
impl Matcher {
    // ...

    pub fn get_referenced_attributes(&self) -> HashSet<&str> {
        let mut attributes: HashSet<&str> = HashSet::new();
        let mut to_visit = vec![&self.expr];
        while let Some(expr) = to_visit.pop() {
            match expr {
                And(l, r) => {
                    to_visit.push(l);
                    to_visit.push(r);
                }
                Or(l, r) => {
                    to_visit.push(l);
                    to_visit.push(r);
                }
                Comparison { attribute, .. } => {
                    attributes.insert(attribute);
                }
            }
        }
        attributes
    }

}

```

**Review by Minoru — APPROVED** [review]
Looks great!
