### PR TITLE
Tell users about all possible locations of the urls file

### LINKED ISSUE #3: Guide users to choosing between dotdir and XDG
**Newsboat version**: 2.10 e171c84de8a67a978a29889067f597a0f0432a1d 

Steps to reproduce the issue:

1. *Do not* create a configuration.

2. Run `newsboat`.

**Expected output**: Newsboat tells me that I don't have the urls configured and suggests creating either `~/.newsboat/urls` or `~/.config/newsboat/urls`.

**Actual output**: Newsboat only tells me about `~/.newsboat/urls`.

### PR DESCRIPTION
**Pull request by Minoru**
Fixes #3. Example output:

```
Starting newsboat r2.19-194-gbf8a...

'urls' file not found. Please create it at one of the following locations:
- /home/testuser/.newsboat/urls
- /home/testuser/.config/newsboat/urls

Newsboat will store the rest of the files accordingly.
```

I did check and it doesn't create the cache file anymore.

Updating the doc turned out to be a challenge. Explaining why we have multiple locations ended up very wordy, and the doc wasn't too lean from the start, so I ended up rewriting half the "quick start" section. Hope we won't bikeshed on this too much :) @der-lyse, can you take a look at doc/chapter-firststeps.asciidoc in this PR?

Reviews from everyone else are welcome too. Will merge in three days.

### CODE REVIEW

File: src/controller.cpp [hunk 1]
```diff
@@ -124,6 +129,32 @@ int Controller::run(const CliArgsParser& args)
...
+						"- %s\n"
+						"\n"
+						"Newsboat will store the rest of the files "
+						"accordingly."),
+					locations.first,
+					locations.second)
+				<< std::endl;
+		}
+
+		return EXIT_FAILURE;
```
Comment (dennisschagt) [inline src/controller.cpp:155]: This breaks the automatic migration from Newsbeuter.

The migration is only executed if the Newsboat urls file does not exist.
But, if the urls file does not exist, this line will make sure that the following line below is not reached:
`const auto migrated = configpaths.try_migrate_from_newsbeuter();`

File: src/controller.cpp [hunk 2]
```diff
@@ -124,6 +129,32 @@ int Controller::run(const CliArgsParser& args)
 		return args.return_code().value();
 	}
 
+	if (!can_open(configpaths.url_file())) {
+		if (!args.silent()) {
+			std::cout << strprintf::fmt(_("Starting %s %s..."),
```
Comment (der-lyse) [inline src/controller.cpp:141]: Does the program name and version really add much value to the user? Also we know at this point, that Newsboat will immediately exit for sure, so the "Starting" is a bit fishy in my point of view. In case you want to keep the program name and version how about "Cannot start %s %s: 'urls' file not found. Please…" and directly continue with the text below?

File: src/controller.cpp [hunk 3]
```diff
@@ -124,6 +129,32 @@ int Controller::run(const CliArgsParser& args)
...
+					PROGRAM_NAME,
+					utils::program_version())
+				<< std::endl;
+
+			std::cout << '\n';
```
Comment (der-lyse) [inline src/controller.cpp:146]: Maybe this gets removed anyways, but is the mix of `'\n'` and `std:endl` here intentional? Couldn't be the first `std::endl` a `'\n'` as well, because the `std::endl` down below will flush stdout?

File: rust/libnewsboat/src/configpaths.rs [hunk 4]
```diff
@@ -82,24 +111,24 @@ impl ConfigPaths {
 
         // hitting this branch means we found a home directory
         // we can now safely call unwrap on all other functions in the dirs crate
-
         config_paths.env_home = env_home.unwrap();
+
+        // This can't panic because we've found the home dir.
+        // This should be replaced with proper error handling after this is not used by c++ anymore
```
Comment (der-lyse) [inline rust/libnewsboat/src/configpaths.rs:117]: This is just a moved code comment, so feel free to ignore: `C++` with an uppercase `C` and a full-stop.

File: doc/chapter-firststeps.asciidoc [hunk 5]
```diff
@@ -1,44 +1,38 @@
...
 	http://rss.cnn.com/rss/cnn_topstories.rss
 	http://newsrss.bbc.co.uk/rss/newsonline_world_edition/front_page/rss.xml
 
+You can also import URLs from your previous reader; see
+<<_other_readers_via_opml,the OPML section for details>>.
+
 If you need to add URLs that have restricted access via username/password, simply
 provide the username/password in the following way:
 
 	http://username:password@hostname.domain.tld/feed.rss
```
[the remark this answers is not in the document]
Comment (Minoru) [reply doc/chapter-firststeps.asciidoc:32]: That's a good note, though. I looked through the docs and made a separate commit that changes many URLs to HTTPS, both example and real ones. (I checked that the real ones still work, too. Some don't yet support HTTPS)

File: src/controller.cpp (hunk 1 above)
Comment (Minoru) [reply src/controller.cpp:155]: Oh, that's embarrassing! The fix was easy though. This time, I did check that migrations do work as intended.

Thanks for spotting this!

File: rust/libnewsboat/tests/configpaths_returns_possible_paths_to_urls_file.rs [hunk 6]
```diff
@@ -0,0 +1,39 @@
...
+
+    env::set_var("HOME", &home);
+
+    if section!("XDG_CONFIG_HOME is set") {
+        let config_home = home.join("configurations");
+        env::set_var("XDG_CONFIG_HOME", &config_home);
+
+        let paths = ConfigPaths::new();
+
+        let expected_dotdir = home.join(".newsboat/urls");
```
Comment (der-lyse) [inline rust/libnewsboat/tests/configpaths_returns_possible_paths_to_urls_file.rs:22]: I personally prefer to actually see the expected final absolute paths in the test code rather than building it in my head (and thus scan through several lines). Yes, a failing test would reveal it, too, but it's not the same. ;-) Additionally, the productive code `join(…)`s the paths as well, so there could be a small potential problem since both use the exact same approach.

File: doc/chapter-firststeps.asciidoc [hunk 7]
```diff
@@ -1,44 +1,38 @@
...
+Newsboat will store the rest of the files accordingly.
 ----
 
-This means that newsboat can't start without any configured feeds. To add
-feeds to newsboat, you can either add URLs to the configuration file
-_$HOME/.newsboat/urls_ or you can import an OPML file by running `newsboat -i
-blogroll.opml`. To manually add URLs, open the file with your favorite text
-editor and add the URLs, one per line:
+Newsboat requires a list of feed URLs, and it supports both traditional
+"dotdirs" and the modern XDG Base Directory locations
```
Comment (der-lyse) [inline doc/chapter-firststeps.asciidoc:15]: Do we want to briefly explain dotdirs here or just hope for the users to be familiar with this? The XDG chapter also tells about it in the fallback without calling it that name, so maybe just change the link text to "more on that later" and add the term "dotdirs" to that chapter?

File: doc/chapter-firststeps.asciidoc (hunk 5 above)
[the remark this answers is not in the document]
Comment (dennisschagt) [reply doc/chapter-firststeps.asciidoc]: Thanks for fixing it!

File: doc/newsboat.asciidoc [hunk 8]
```diff
@@ -264,17 +264,17 @@ are met:
 * none of `-u`, `-c`, `-C` options were specified; and
 
 * the urls file doesn't exist (neither _~/.newsboat/urls_ nor
-  _$XDG_CONFIG_DIR/newsboat/urls_).
+  _$XDG_CONFIG_HOME/newsboat/urls_).
```
Comment (dennisschagt) [inline doc/newsboat.asciidoc:267]: Good catch.

I've seen before that `$XDG_CONFIG_DIR` wasn't defined on my system but never really thought anything about it.
I guess this explains it.

File: doc/chapter-firststeps.asciidoc [hunk 9]
```diff
@@ -1,44 +1,38 @@
...
+(<<_xdg_base_directory_support,more on XDG support later>>). The _urls_ file is
```
[the remark this answers is not in the document]
Comment (Minoru) [reply doc/chapter-firststeps.asciidoc:16]: Was the problem caused by the word "indicator"? I'd like to adopt your suggestion with a little edit: "The placement of the urls file *indicates* the location you want to use." It's probably just pedantry, but "determines" would imply that the file dictates something to you, whereas in fact it merely *indicates* your preference.

File: rust/libnewsboat/src/configpaths.rs [hunk 10]
```diff
@@ -25,10 +25,36 @@ const CMDLINE_HISTORY_FILENAME: &str = "history.cmdline";
 
 #[derive(Debug, Default)]
 pub struct ConfigPaths {
+    /// Path to the user's home directory
+    ///
+    /// Can be empty, in which case `error_message` should contain an explanation
```
[the remark this answers is not in the document]
Comment (Minoru) [reply rust/libnewsboat/src/configpaths.rs:30]: I couldn't find anything in [the API guidelines](https://rust-lang.github.io/api-guidelines/about.html), but the standard library puts full-stops after everything, so let's do that.

File: doc/chapter-firststeps.asciidoc (hunk 9 above)
[the remark this answers is not in the document]
Comment (der-lyse) [reply doc/chapter-firststeps.asciidoc:16]: I tried to figure that out, but I cannot remember exactly. My best bet, however, would be the "indicator", too.

Your version is absolutely fine with me. I'm wondering whether we should stress that **only** the _urls_ file is used to determine the directory structure to use. Of course we haven't introduced the other files yet at this point (when reading straight from the top), but a more familiar user might have _config_, _cache.db_ and others in mind.

Well, the file dictates my preference *to Newsboat*.

File: src/controller.cpp (hunk 2 above)
Comment (Minoru) [reply src/controller.cpp:141]: I added this because the error message alone looked a bit weird to me. With this message, both the "happy path" and the error case begin with "Starting …", which is a nice uniformity.

But Newsbeuter migration doesn't print this either, and I agree with your arguments that it's fishy. So I guess I'll just remove this line altogether.

File: src/controller.cpp (hunk 3 above)
Comment (Minoru) [reply src/controller.cpp:146]: [This will be removed](https://github.com/newsboat/newsboat/pull/907#discussion_r414707165).

File: rust/libnewsboat/src/configpaths.rs (hunk 4 above)
Comment (Minoru) [reply rust/libnewsboat/src/configpaths.rs:117]: This isn't a doc comment, so I wouldn't enforce any style here. But I'll fix it anyway :)

**Comment by der-lyse** [comment]
It just occurred to me that the default value for the [`cache-file`](https://newsboat.org/releases/2.19/docs/newsboat.html#cache-file) setting in the _Configuration Commands_ table needs to account for the directory structure choice as well. But maybe that's left after the [tables are turned into lists](https://github.com/newsboat/newsboat/issues/441) when we can use bullet lists.

Also [`urls-source`](https://newsboat.org/releases/2.19/docs/newsboat.html#urls-source)'s description talks about `~/.newsboat/urls`.

Well, now that I actively had a look there are several places which need adaption. This is going to get out of scope for this PR quickly.

File: doc/chapter-firststeps.asciidoc (hunk 7 above)
Comment (Minoru) [reply doc/chapter-firststeps.asciidoc:15]: This is a "quick start" section, so I'd prefer to keep it as concise as possible. I'll take your suggestion and explain it in the XDG section. Thanks!

File: doc/chapter-firststeps.asciidoc (hunk 9 above)
[the remark this answers is not in the document]
Comment (Minoru) [reply doc/chapter-firststeps.asciidoc:16]: Okay, I'll apply my suggestion then.

> I'm wondering whether we should stress that only the urls file is used to determine the directory structure to use.

Doesn't the error message do that already? It says "Newsboat will store the rest of the files accordingly." Or by stress you mean repeating that once again, to make sure the user doesn't miss that? I'm not sure that repetition will be very effective.

**Comment by Minoru** [comment]
> Well, now that I actively had a look there are several places which need adaption. This is going to get out of scope for this PR quickly.

Thanks for thinking about the settings and the rest of the docs! I'll submit a separate PR.

File: rust/libnewsboat/src/configpaths.rs (hunk 10 above)
[the remark this answers is not in the document]
Comment (Minoru) [reply rust/libnewsboat/src/configpaths.rs]: Correction: API guidelines reference RFC 505, which [says to use full punctuation](https://github.com/rust-lang/rfcs/blob/master/text/0505-api-comment-conventions.md#formatting).

File: doc/chapter-firststeps.asciidoc (hunk 9 above)
[the remark this answers is not in the document]
Comment (der-lyse) [reply doc/chapter-firststeps.asciidoc]: I just meant to emphasize that it's the _urls_ file and only the _urls_ file, none of the others, which is the single source of truth regarding directory structure. But yes, I agree, in combination with the program output this is actually pretty clear. I just had the documentation in mind without taking the quoted error message into account and my fictional scenario where this would help turns out to be invalid now as I think of it.

File: src/controller.cpp (hunk 2 above)
Comment (der-lyse) [reply src/controller.cpp]: > With this message, both the "happy path" and the error case begin with "Starting …", which is a nice uniformity.

Indeed, I never realized that.

**Comment by Minoru** [comment]
Thanks for the reviews, guys!

**Comment by carno** [comment]
Is this expected that after this users with existing configuration (using tt-rss) will be forced to create a dummy `urls` file to have `newsboat` start again?

**Comment by Minoru** [comment]
@carno Oh no, it wasn't.

That's even more embarrassing than breaking the Newsbeuter migration. I was misled by our own error message: I thought "urls" file is used to figure out what directory to use, but [in reality](https://github.com/newsboat/newsboat/blob/5c8ff095fa0f0c481e5c893e43e8293c0358ac4c/rust/libnewsboat/src/configpaths.rs#L295-L297) we just check if XDG confg directory exists.

I reverted this PR in https://github.com/newsboat/newsboat/commit/6a4e5af4449fd25964295cf8322ca69273e30378, and cherry-picked the commits that improved docs.

Thank you for spotting this, @carno!
