### PR TITLE
Fix for "Make Inoreader 'sort by firsttag' useful" #1128

### LINKED ISSUE #1128: Make Inoreader 'sort by firsttag' useful
**newsboat 2.20.1**:

Hello everyone,

I've been pretty annoyed since I've started using Inoreader with this problem. When I wanted to sort my feed with the 'firsttag' option, I assumed it would sort it by folder name which would be pretty useful. Instead for some reason, it sorts the feed by title name, making it useless IMO since there is already an option for that.

So I started digging though the code, and I found out a solution for this. Looking at the following block of code:

https://github.com/newsboat/newsboat/blob/2e8c2aa58eacc669f50733d681bbf571be1f4ab5/src/inoreaderapi.cpp#L145-L163

We can see that the title is pushed to the tags list first than the folders names, making it the cause of the problem. If we moved the 'title tag' block after the 'for loop', then the 'firsttag' sorting option would sort the feed by folder names, making it in my opinion much more useful. I've already tried it locally an it works fine to me.

Please let me know what you all think of this.
Cheers!
José Rui

### PR DESCRIPTION
**Pull request by JRuiBarros**
Fixes #1128 

Please check the commit messages for all the needed information.

### CODE REVIEW

**Comment by JRuiBarros** [comment]
Thanks for the suggestions @Minoru, as I'm rusty on testing and I have no experience on testing in C++. I've uploaded your suggested fixes and please let me know what you think.

File: test/rssfeed.cpp [hunk 1]
```diff
@@ -261,23 +261,33 @@ TEST_CASE("RssFeed::get_firsttag() returns first tag", "[RssFeed]")
...
+		REQUIRE(f.get_firsttag() == "");
+	}
 
-	std::vector<std::string> tags = {"One", "Two", "Three", "Four"};
-	f.set_tags(tags);
-	REQUIRE(f.get_firsttag() == "One");
+	SECTION("Ordinary tags") {
+		std::vector<std::string> tags = {"One", "Two", "Three", "Four"};
+		f.set_tags(tags);
+		REQUIRE(f.get_firsttag() == tags[0]);
```
Comment (Minoru) [inline test/rssfeed.cpp:271]: Whenever possible, use literal values in assertions, because:

1. when an assertion fails, the values are printed out. Seeing both the result and the expected value makes it quicker to debug, since you don't have to look up the test and find out what `tags[0]` contains;
2. tests in general should be as "obvious" as possible, even at the expense of some repetition.

Also, `tags` are never modified, so either mark it `const` or drop it altogether (you can construct a vector right in the call to `set_tags`: `set_tags({"one", "two", "three"})`. Marking everything `const` makes it harder to commit certain errors, and also documents your intent better.

(This applies to all the other sections, below.)

Comment (JRuiBarros) [reply test/rssfeed.cpp]: Got it, new commit uploaded.

**Comment by Minoru** [comment]
Ah, [Travis actually finished already](https://travis-ci.com/github/newsboat/newsboat/builds/179335353), but GitHub didn't notice this again.

**Comment by JRuiBarros** [comment]
Thanks @Minoru for your guidance as well.
