### PR TITLE
Podboat: Show human readable download speed

### LINKED ISSUE #727: Podboat shows speed as 0.0kb/s if actual speed is higer than 10MB/s
**Newsboat version**: 2.18.0

Caused by [check in poddlthread.cpp](https://github.com/newsboat/newsboat/blob/f80387f9c4a496258d6839bc472c8a0dc6b9e58f/src/poddlthread.cpp#L182-L183).

Steps to reproduce the issue:

1. Add a download to the podboat download queue

2. Start the download

3. Observe that a speed of 0.0kb/s is shown if the actual download speed rises above 10MB/s

**Other info you think is relevant**:
I expect the check was added to make sure that the speed fits in the download speed field.
The following image shows that the speed would not fit if another digit would be added:
image

### PR DESCRIPTION
**Pull request by dennisschagt**
Fixes #727.

### CODE REVIEW

File: src/configcontainer.cpp [hunk 1]
```diff
@@ -168,7 +168,7 @@ ConfigContainer::ConfigContainer()
 		ConfigData("no", ConfigDataType::BOOL)},
 	{
 		"podlist-format",
-		ConfigData( "%4i [%6dMB/%6tMB] [%5p %%] [%7k kb/s] %-20S %u -> %F", ConfigDataType::STR)},
+		ConfigData( "%4i [%6dMB/%6tMB] [%5p %%] [%12k] %-20S %u -> %F", ConfigDataType::STR)},
```
Comment (dennisschagt) [inline src/configcontainer.cpp]: Regarding `%12k`:
`xxx.xx xB/s` is only 11 characters, allowing for a 1 char longer translation for KB/s (e.g. if some translator uses `KiB/s` or `MiB/s`).

If longer translations are added, the end will be cut of when printing.
Not sure if it is worth fixing such a potential problem now.

File: src/poddlthread.cpp [hunk 2]
```diff
@@ -179,11 +179,6 @@ int PodDlThread::progress(double dlnow, double dltotal)
 	}
 	gettimeofday(&tv2, nullptr);
 	double kbps = compute_kbps();
```
Comment (Minoru) [inline src/poddlthread.cpp]: This can be made `const` now.

File: src/configcontainer.cpp (hunk 1 above)
Comment (Minoru) [reply src/configcontainer.cpp]: I think it can also be 12 characters, e.g. "1023.99 xB/s". Can't in?

> Not sure if it is worth fixing such a potential problem now.

I wouldn't. The problem doesn't seem too dire: translators can always use the English terms, which might look a bit lame in between translated text, but will be understood by the user all right.

What I *would* fix is the alignment: `%12k` pads on the right, so if I have two speeds, "123.45 KB/s" and "1.05 GB/s", they won't line up nicely:

```
... |123.45 KB/s | ...
... |1.05 GB/s   | ...
```

I'd use `%-12k` there, for left padding:

```
... | 123.45 KB/s| ...
... |   1.05 GB/s| ...
```

File: src/pbview.cpp [hunk 3]
```diff
@@ -367,13 +380,17 @@ std::string PbView::format_line(const std::string& podlist_format,
...
+	const auto speed = get_speed_human_readable(speed_kbps);
+
 	fmt.register_fmt('i', strprintf::fmt("%u", pos + 1));
 	fmt.register_fmt('d',
 		strprintf::fmt("%.1f", dl.current_size() / (1024 * 1024)));
 	fmt.register_fmt(
 		't', strprintf::fmt("%.1f", dl.total_size() / (1024 * 1024)));
 	fmt.register_fmt('p', strprintf::fmt("%.1f", dl.percents_finished()));
-	fmt.register_fmt('k', strprintf::fmt("%.2f", dl.kbps()));
+	fmt.register_fmt('k', strprintf::fmt("%.2f %s", speed.first,
```
Comment (Minoru) [inline src/pbview.cpp]: I'd prefer to introduce a new specifier, `K`, so people's custom settings aren't broken, and those who like the old default can go back to it.

File: src/pbview.cpp [hunk 4]
```diff
@@ -367,13 +380,17 @@ std::string PbView::format_line(const std::string& podlist_format,
...
+			speed.second.c_str()));
```
Comment (Minoru) [inline src/pbview.cpp]: `strprintf::fmt` accepts `std::string`, so no need to call `.c_str()` here.

File: src/configcontainer.cpp (hunk 1 above)
Comment (dennisschagt) [reply src/configcontainer.cpp]: > What I would fix is the alignment: `%12k` pads on the right

The documentation tells the same thing

> positive numbers indicate that the text that is inserted for the sequence shall be padded right to a total width that is specified by the number, while negative number specify left padding

but it looks like it is working exactly the other way around (at least in this case).
By default it is right aligned and when I apply your suggestion (`12k`->`-12k`) al text is printed on the left which results in ugly misalignment.

- [ ] I will look into this



> I think it can also be 12 characters, e.g. "1023.99 xB/s". Can't in?

You're right, I guess that is possible.

File: src/pbview.cpp (hunk 3 above)
Comment (dennisschagt) [reply src/pbview.cpp]: Good idea

- [ ] Implement

**Comment by dennisschagt** [comment]
I saw your comment on [a different PR](https://github.com/newsboat/newsboat/pull/729#issuecomment-578487362) about using `git commit --fixup=<commit-hash>`.

I've now used that instead of rebasing/squashing.

You mentioned running  `git rebase --interactive --autosquash master`.
Do you want me to run that (after a review approval) or do you rather to do that yourself?

File: src/configcontainer.cpp (hunk 1 above)
Comment (dennisschagt) [reply src/configcontainer.cpp]: It looks like the documentation has left/right inverted with respect to padding (or padding/alignment was mixed up).

I've created a pull request to fix the documentation: https://github.com/newsboat/newsboat/pull/745
I expect that resolves this part (if I'm not mistaken regarding the padding).

**Comment by dennisschagt** [comment]
I took care of each of your comments.

Thanks for the review!

**Comment by Minoru** [comment]
> You mentioned running git rebase --interactive --autosquash master. Do you want me to run that (after a review approval) or do you rather to do that yourself?

Well, we've never really done it with any other contributor yet, so I don't know :) Let's experiment. I think it makes sense for me to try to run that, and if no conflicts arise, I'll just push the result. If there are conflicts, I'll ask the contributor if they want to resolve them, or I should just merge it as-is.

**Comment by Minoru** [comment]
It rebased without conflicts, so I'm merging it without waiting for the build to finish. Thank you for the PR!
