### PR TITLE
Fix semicolons in macro operations' arguments breaking parsing

### LINKED ISSUE #1200: Can't parse macros with semicolons in their arguments
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: 2.21.0

Previously, I had this macro in my config file, to save a selected article to Pocket:

```
macro s set browser "{ open -gj 'pocket://add?url=%u' && sleep 3 && killall Pocket; } 1>/dev/null 2>&1 & disown"; open-in-browser ; set browser "open -g '%u'"
```

The aim was to group the three commands (`open`, `sleep`, `killall`) using braces, and background/disown them together, so that I could continue using Newsboat while the article was being saved.

However, since the new update (presumably because of the point "It is now a startup error for a macro to have no operations"), I get the following error while starting Newsboat:

> Starting newsboat 2.21.0...
> Loading configuration...Error while processing command \`macro s set browser "{ open -gj 'pocket://add?url=%u' && sleep 3 && killall Pocket; } 1>/dev/null 2>&1 & disown"; open-in-browser ; set browser "open -g '%u'"' (~/.config/newsboat/config line 59): \`}' is not a valid operation

Is this intended? Also, is there currently any way to achieve what I'm trying to do (i.e. group multiple shell commands together, redirect their streams, and disown them together) without getting a start-up error?

Edit: I understand it's also possible to do it using an external script and then calling the script from the macro, but I'd prefer if it were possible to avoid external scripts. My question is more regarding whether this is intended as a change that breaks command grouping, or if it was just missed when detecting operations in macros.

### PR DESCRIPTION
**Pull request by Minoru**
That title is a mouthful. This commit fixes #1200, so just read that issue for the reproduction steps.

Reviews are welcome as always. Will merge once @dennisschagt approved this, or in three days if no issues are raised.

### CODE REVIEW

**Comment by Minoru** [comment]
Clang 11 is apparently gone from the apt.llvm.org repo again. Just ignore this failure for now; I'll restart the build sometime later. This will ultimately get resolved when Clang 11 gets released; should receive fewer updates then, and everything will become much more stable.

File: src/keymap.cpp [hunk 1]
```diff
@@ -740,15 +740,29 @@ void KeyMap::handle_action(const std::string& action, const std::string& params)
...
 std::vector<MacroCmd> KeyMap::parse_operation_sequence(const std::string& line)
 {
-	const auto operations = utils::tokenize_quoted(line, ";");
+	const auto words = utils::tokenize_quoted(line, " ");
+
+	std::vector<std::string> tokens;
+	for (auto word : words) {
+		if (word.size() > 1 && word.back() == ';') {
+			// Found a token with no space between the command and the
+			// semicolon; let's split it in two tokens
```
Comment (dennisschagt) [inline src/keymap.cpp:749]: It looks like this does not handle semicolons when there is no space around them.
A configuration like `macro x open;open-in-browser;quit` seems to work on the current master branch but no longer works after applying this PR.

File: test/keymap.cpp [hunk 2]
```diff
@@ -519,3 +518,32 @@ TEST_CASE("Regression test for macro configuration semicolon handling",
 		REQUIRE(macros[1].args == std::vector<std::string>({}));
 	}
 }
+
+TEST_CASE("It's not an error to have no operations before a semicolon in "
+	"a macro",
+	"[KeyMap]")
+{
+	KeyMap k(KM_NEWSBOAT);
+	k.handle_action("macro", "r ; ;; ; open");
```
Comment (dennisschagt) [inline test/keymap.cpp:527]: Seeing that `;;` is accepted, I would expect any number of consecutive semicolons to be accepted (not important at all, feel free to ignore).

File: src/keymap.cpp [hunk 3]
```diff
@@ -758,6 +772,23 @@ std::vector<MacroCmd> KeyMap::parse_operation_sequence(const std::string& line)
...
+
+			command_name.reset();
+			arguments.clear();
+		} else {
+			arguments.push_back(token);
+		}
+	}
+
+	if (command_name.has_value()) {
+		add_macro();
```
Comment (dennisschagt) [inline src/keymap.cpp:791]: Very minor: `add_macro()` already checks if `command_name` has a value.

**Comment by Minoru** [comment]
Thank you for spotting the problem with spaces around semicolons!

It appears that an input line can't be correctly tokenized with `utils::tokenize_quoted` at all, no matter what delimiter we specify. Given an input of `macro x set browser "sleep 3 ; firefox %u ; sleep 3" ";open";toggle-article-read;quit`:

1. splitting by spaces gives us the following tokens:

    * `macro`
    * `x`
    * `set`
    * `browser`
    * `sleep 3 ; firefox %u ; sleep 3`
    * `;open`
    * `;toggle-article-read;quit`

    Here, the last two operations are bunched up into a single token. We can't just split tokens on semicolons because that'll break the "browser" value. We also can't tell if a given token is really a sequence of ops, or is it an argument (i.e. we can't say which of the last two tokens was in quotes in the input string).

2. splitting by semicolons:

    * `macro x set browser "sleep 3 `
    * ` firefox %u `
    * ` sleep 3" "`
    * `open`
    * `toggle-article-read`
    * `quit`

    Here, double quotes are not respected since `"` characters aren't at the beginning of the tokens. The last few operations are extracted correctly, but the first one, along with its argument, is hopelessly broken.

3. splitting by spaces *and* semicolons:

    * `macro`
    * `x`
    * `set`
    * `browser`
    * `sleep 3 ; firefox %u ; sleep 3`
    * `;open`
    * `toggle-article-read`
    * `quit`

    This looks like a solution to all our problems, until you realize that we can no longer tell arguments from operations, because semicolons are missing from the token list.

One possible solution for this is to extend `utils::tokenize_quoted` to return the delimiters as tokens. We could then split by both spaces and semicolons, use semicolons as indicators of where operations start, and just skip the spaces. This likely doesn't require a lot of code, but `utils::tokenize_quoted` is complicated enough already.

What I'll try instead is writing an actual parser. We already include the Nom crate, and we have means to add FFI from C++ to Rust, so this seems a pretty low-risk endeavour.

The end result is likely to have little in common with what I already posted here, so I'll just force-push it.

**Comment by Minoru** [comment]
Sorry for the long radio silence — I wasn't able to give this much attention the past few weeks.

I'm now at a point where I have a working parser in Rust. I'm not requesting a review just yet, but if you're curious, take a look at the final patch (the history is messy, I'll clean it up later).

What remains is to drag an `Option<Vec<Vec<String>>>` over the FFI boundary. This is a bit of challenge because `Vec` can't be turned into a single owning pointer like `String` can. We'll have to decompose `Vec` into three "raw parts", put all of them into a struct, fling that over FFI, use it, then fling that struct back for Rust to re-construct the `Vec` and deallocate it properly. There's a high chance of memory corruption and leaks in that code :(

I hope to get something working over the next couple days, but for now, I'm marking this PR as a draft.

**Comment by Minoru** [comment]
> We'll have to decompose Vec into three "raw parts", put all of them into a struct, fling that over FFI, use it, then fling that struct back for Rust to re-construct the Vec and deallocate it properly. There's a high chance of memory corruption and leaks in that code :(

I also have a plan B for this: use the cxx crate. I experimented with in the feature/cxx branch; it doesn't pass CI. Overall I feel like that crate is the future of our FFI bindings, so perhaps I should forgo the above idea and concentrate on it exclusively. We'll see :)

**Comment by Minoru** [comment]
I went straight for plan B, since I'd like to migrate to the cxx crate anyway. It [almost works](https://github.com/newsboat/newsboat/runs/1233878859). I think I know what causes the remaining failures, but I'm still thinking on how to best fix it. Almost there!

**Comment by Minoru** [comment]
I only spent something like 6 hours on cxx over the last few weeks, but there's a bit of news to report.

I managed to make all but one jobs succeed. The remaining one is "Clang 10 with extra checks". My every attempt at fixing it results in breaking other jobs again. Overall, it seems there are two general problems:

1. *`make -jN all test` compiles two versions of cxx bridge into the same output files, which is a race*. `all` depends on a release version of `libnewsboat-ffi` crate, while `test` depends on a debug version. The bridge is stored in target/cxxbridge.

    I can think of a few ways to avoid a race, but they are all hacky: 1) require `all` to finish before `test` begins (this limits parallelism); 2) compile tests in release mode too (this limits their usefulness as integer over- and underflows no longer panic).

2. *with Clang 10, the bridge is compiled slightly differently for `make test/test` and `make rust-test`* ([here's a log](https://cirrus-ci.com/task/5852406917365760)). I haven't dug further than Make targets; it seems like I'll need more control over how Cargo compiles C++, and I doubt I'll get that control from the `cc` crate. But that's just a hunch; as I said, I didn't dig to the root cause.

Both problems stem from the fact that I tried to "cheat" and build the bridge using Cargo. The "proper solution", it seems, is to do it from the Makefile instead. This requires builders to install `cxxbridge-cmd` utility, though. I'm trying this approach now.

**Comment by Minoru** [comment]
cxxbridge-cmd fixes the first issue, but the second one is still there (albeit the exact error is a little bit different). Oh well, I'll take that I guess :)

**Comment by Minoru** [comment]
I got cxx crate working in [the feature/cxx-try-3 branch](https://github.com/newsboat/newsboat/tree/feature/cxx-try-3), but:

1. I had to drop support for GCC 4.9, since it doesn't implement `std::is_trivially_move_constructible` which cxx requires;

2. I had to perform dirty tricks with `CARGO_TARGET_DIR` env var to get cxx to work properly;

3. I had to use an older version of the crate, because the current 1.0.1 requires Rust 1.48 and C++14;

4. furthermore, the branch doesn't even compile with 1.0.1, since that version requires the bridges to reside in the same crate as the types they use ("libnewsboat" crate, in our case). If we move bridges there, we won't be able to add integration tests to that crate.

    Perhaps we can switch things around: make "libnewsboat" a static lib, move bridges in there, and create a separate "libnewsboat-tester" crate that depends on "libnewsboat", re-exports all its APIs and uses them in integration tests.

    Anyway, this limitation is mentioned in the cxx book, and it's noted there that it might get lifted in the future. We have to wait until March to use Rust 1.48 anyway, so this issue is not an urgent one for us;

5. my branch doesn't display stack traces when non-UTF-8 `std::string` is converted to Rust's `String` — it simply aborts because `std::invalid_argument` is not handled. Our existing bindings provide stacktraces because each binding is wrapped in a macro that catches panics. With cxx, we often don't have anything to wrap — indeed, it's the point of cxx that it writes the bindings for us.

    I see two ways to restore that functionality:

    1. wrap each *call* to the wrapped function in a `try { /* the call */ } catch (const std::invalid_argument& e) { /* print a stacktrace and abort */ }`. This is tedious and requires a way to obtain the stacktrace (like Boost::stacktrace — yet another dependency);

    2. don't catch that exception at all. Install a SIGABRT handler and use [`backtrace()`](https://man7.org/linux/man-pages/man3/backtrace.3.html) to figure out the call stack that led to the signal. Despite a note in the man page, this call is also available on BSDs and macOS. (Suggested by @pink-snow.)

    Finally, we can drop stacktraces altogether. They are useful, but (luckily) rare. Without a stacktrace, the only info we'd have is the type of the exception and its message. I feel like with a good, reproducible report this is enough: one of developers would just run Newsboat with the same config, get the same error, and use a debugger to find the cause.

A word on bindgen: I haven't tried it lately, but it feels like it's going to save us just a bit of coding, but require integration into the build system — and libclang, even for GCC builds. Probably has the same problem with stacktraces as cxx does. Overall, I don't consider it as an option, but if someone has experience with it and would like to advocate for it — please go ahead.

All of the above makes me reconsider the use of cxx. On the one hand, it's a pretty heavy dependency with a lot of caveats. On the other, while working with it, I got a new appreciation of how much work is required to pass something like `Vec` from Rust to C++. I think re-creating that by hand would be a huge distraction, and, ultimately, a useless one, since all that code is going away once we drop C++. With this PR *and* FilterParser/Matcher both blocked on FFI, it's probably time to bite the bullet and take a less perfect, but working, solution.

I think I've pretty much made the decision by now :) But I still wrote this comment to get my thoughts in order, and I'll sleep on this to make sure I'm not picking cxx out of frustration and sunk costs fallacy.

**Comment by Minoru** [comment]
Merging #1317 caused conflicts for this PR, I'll rebase it in a few minutes.

File: rust/libnewsboat/src/keymap.rs [hunk 4]
```diff
@@ -0,0 +1,288 @@
...
+    parser(input)
+}
+
+fn token(input: &str) -> IResult<&str, String> {
+    let mut parser = alt((quoted_token, unquoted_token));
+    parser(input)
+}
+
+fn operation_with_args(input: &str) -> IResult<&str, Vec<String>> {
+    let mut parser = separated_list1(many1(tag(" ")), token);
```
Comment (dennisschagt) [inline rust/libnewsboat/src/keymap.rs:42]: I think `many1(tag(" "))` can be replaced with `space1`.

File: rust/libnewsboat/src/keymap.rs [hunk 5]
```diff
@@ -0,0 +1,288 @@
...
+    bytes::complete::{escaped_transform, is_not, tag, take},
+    character::complete::{none_of, space0},
+    combinator::{complete, eof, map, recognize, value},
+    multi::{many0, many1, separated_list0, separated_list1},
+    sequence::{delimited, tuple},
+    IResult,
+};
+
+fn unquoted_token(input: &str) -> IResult<&str, String> {
+    let parser = tuple((none_of("\";"), is_not(" ;")));
```
Comment (dennisschagt) [inline rust/libnewsboat/src/keymap.rs:12]: This does not allow single-character unquoted tokens.
Can be reproduced with a test case like:
```
    #[test]
    fn t_tokenize_operation_sequence_allows_single_character_unquoted() {
        assert_eq!(
            tokenize_operation_sequence(r#"set a b"#).unwrap(),
            vec![vec!["set", "a", "b"]]
        );
    }
```

**Review by dennisschagt — CHANGES_REQUESTED** [review]
Found a small issue.
Other than that, looks good!

File: rust/libnewsboat-ffi/src/keymap.rs [hunk 6]
```diff
@@ -0,0 +1,48 @@
...
+}
+
+struct Operation {
+    tokens: Vec<String>,
+}
+
+fn tokenize_operation_sequence(input: &str) -> Vec<Operation> {
+    match libnewsboat::keymap::tokenize_operation_sequence(input) {
+        Some(mut operations) => operations
+            .drain(0..)
```
[the remark this answers is not in the document]
Comment (Minoru) [reply rust/libnewsboat-ffi/src/keymap.rs]: None. Thanks for pointing out the `IntoIter` instance — I only looked at `iter()` and `iter_mut()` methods, and those didn't work because they didn't allow me to move elements out of the vector. `into_iter()` works flawlessly here, so I added it in https://github.com/newsboat/newsboat/pull/1203/commits/5eacbfc0c0597eab002387dcb9a5efc59faa10e4.

File: rust/libnewsboat/src/keymap.rs (hunk 5 above)
Comment (Minoru) [reply rust/libnewsboat/src/keymap.rs]: Right, thanks! I added a corresponding C++ test in https://github.com/newsboat/newsboat/pull/1203/commits/b8f019bbd4409850b86a89ed710431e13d247bbc (it passes on master too), then fixed the bug in https://github.com/newsboat/newsboat/pull/1203/commits/3a5a76de6c4093637c3f8944b632bb1bffd3a4a1.

**Review by dennisschagt — APPROVED** [review]
:+1:
