### PR TITLE
Do not exit when preparing invalid query feed

### LINKED ISSUE #1665: Newsboat crashes when entering query-feed with unknown attribute
**Newsboat version**: 8660096598c23a797a405c769565f516a09dd22a (current master)

Config file:
```
# empty
```

URLs file:
```
https://newsboat.org/news.atom newsboat
"query:invalid query:tag = \"newsboat\""
```

Steps to reproduce the issue:

1. Start newsboat

2. Select second feed and press ENTER

**Other info you think is relevant**:
image

### PR DESCRIPTION
**Pull request by Minoru**
Fixes #1665.

This can't be merged right now because it introduces a new translatable string. However, @dennisschagt provided a good stopgap solution in #1666, so it's not a very big deal. I'll merge after the 2.24 release.

### CODE REVIEW

File: src/view.cpp [hunk 1]
```diff
@@ -904,7 +958,13 @@ bool View::get_prev_feed(ItemListFormAction& itemlist)
 {
 	unsigned int feedpos;
 	if (feedlist_form->jump_to_previous_feed(feedpos)) {
-		prepare_query_feed(feedlist_form->get_feed());
+		try {
+			prepare_query_feed(feedlist_form->get_feed());
```
Comment (dennisschagt) [inline src/view.cpp:962]: Looks like this `prepare_query_feed()` call, together with the exact same exception handling, is repeated quite a few times.
Would it be possible to move the exception handling into `prepare_query_feed`, return a bool from it, and change these lines to the following?
```
if (!prepare_query_feed(feedlist_form->get_feed())) {
	return false;
}
```

**Review by dennisschagt — APPROVED** [review]
LGTM

File: src/view.cpp (hunk 1 above)
Comment (Minoru) [reply src/view.cpp:962]: Yeah, I was debating this with myself too. On one hand, DRY requires to put all this error handling into `prepare_query_feed()`. On the other hand, `prepare_query_feed()` shouldn't even be a part of `View`, since query feed have nothing to do with views. Instead, it should be a method on `RssFeed` which returns an error, which is then handled in the calling code. In the end, I decided to do it that way so we don't have to refactor it later.

Does this sound acceptable, or am I just being lazy here? :)

Comment (dennisschagt) [reply src/view.cpp:962]: Sounds good

**Comment by Minoru** [comment]
Thank you for reviewing :)
