### PR TITLE
Fix alignment issues in format strings

### LINKED ISSUE #139: Unicode characters with >=2 code points breaks the alignment of format strings
<details>
 <summary>newsboat -v</summary>

```
newsboat 2.10.2 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2017 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017 Newsboat contributors

newsboat is free software and licensed under the MIT License.
Type `newsboat -vv' for more information.

newsboat 2.10.2
System: Darwin 16.7.0 (x86_64)
Compiler: g++ 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)
ncurses: ncurses 5.7.20081102 (compiled with 5.7)
libcurl: libcurl/7.54.0 SecureTransport zlib/1.2.8 (compiled with 7.51.0)
SQLite: 3.16.0 (compiled with 3.16.0)
libxml2: compiled with 2.9.4
```

</details>
<br>

It's rather self-explanatory, see the line with emojis. I believe it's because newsboat is counting the code points of characters, since one emoji contains two 2 code points (a surrogate pair), it breaks the alignment.

```
articlelist-format "  %t %> %L  %D  "
```

image

### LINKED ISSUE #683: Multi-byte unicode characters in article titles spoil layout of article list
### Issue ###

On my system, when using an articlelist format that left-aligns a field with a fixed width,
and the article title contains emojis (which are multi-byte unicode characters, I assume), 
apparently the number of characters of the article title, which is used to calculate
the position of the first character of the following field on the screen, is counted wrong. 

For each emoji that is used in the article title, the first character of the following field 
is shifted one place to the right.

See the sample of an article list at the bottom of this post.

### Operation System ###

Debian Stretch

Note: newsboat was installed with linuxbrew.

### Locale ###

```
LANG=de_DE.UTF-8
LANGUAGE=
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
```

### Newsboat Versions ###

```
newsboat 2.17.1
System: Linux 4.9.0-11-amd64 (x86_64)
Compiler: g++ 5.5.0
ncurses: ncurses 6.1.20180127 (compiled with 6.1)
libcurl: libcurl/7.66.0 OpenSSL/1.0.2t zlib/1.2.11 (compiled with 7.66.0)
SQLite: 3.29.0 (compiled with 3.29.0)
libxml2: compiled with 2.9.9
```

### Config ###

```
datetime-format "%Y-%m-%d"
articlelist-format "%4i %f %-60t %D"
```

### Feed URL ###

https://www.youtube.com/feeds/videos.xml?channel_id=UCZiL6BoryLWxyapUuVYW27g

(This is the RSS feed of videos in a YouTube channel)

### Article list ###

```
   9 N  How to upgrade Linux Mint 19.1 to 19.2                       2019-08-07
  10 N  CloudBerry Backup for Linux Server 💽 with web interface 😱    2019-07-31
  11 N  15 Things to do After Installing elementary OS (2019)        2019-07-27
  12 N  Picture in picture in Elementary OS                          2019-07-19
  13 N  SUDO: another fun program? 🤔                                 2019-07-13
```

### PR DESCRIPTION
**Pull request by dennisschagt**
Fixes #139 
Fixes #683 

Also fixes old Newsbeuter issues:
- Fixes https://github.com/akrennmair/newsbeuter/issues/562
- Fixes https://github.com/akrennmair/newsbeuter/issues/572

I'm slowly going through [the rust-lang book](https://doc.rust-lang.org/stable/book) but am far from finishing it.
Feel free to let me know if you see ways to improve the Rust code I write.

### CODE REVIEW

File: rust/libnewsboat/src/utils.rs [hunk 1]
```diff
@@ -288,6 +288,17 @@ pub fn strwidth(rs_str: &str) -> usize {
     UnicodeWidthStr::width(rs_str)
 }
 
+/// Returns the with of `rs_str` when displayed on screen.
```
Comment (Minoru) [inline rust/libnewsboat/src/utils.rs]: A typo: "Returns the *width*…"

File: rust/libnewsboat/src/fmtstrformatter/mod.rs [hunk 2]
```diff
@@ -353,6 +353,40 @@ mod tests {
         assert_eq!(fmt.do_format("%?c?asdf?", 0), "asdf");
     }
 
+    #[test]
+    fn t_do_format_keeps_wide_characters_within_specified_width() {
```
Comment (Minoru) [inline rust/libnewsboat/src/fmtstrformatter/mod.rs]: These four tests have to be ported to C++, to ensure that FFI bindings don't change the behaviour and don't introduce any bugs.

File: rust/libnewsboat/src/fmtstrformatter/limited_string.rs [hunk 3]
```diff
@@ -32,16 +22,16 @@ impl LimitedString {
         }
     }
 
-    /// Returns the number of graphemes in the string.
+    /// Returns the "displayed width" of the string
     pub fn length(&self) -> usize {
-        utils::graphemes_count(&self.content)
```
Comment (Minoru) [inline rust/libnewsboat/src/fmtstrformatter/limited_string.rs]: Are there any other users of `utils::graphemes_count`? Can that function be removed now?

File: rust/libnewsboat/src/fmtstrformatter/limited_string.rs [hunk 4]
```diff
@@ -55,7 +45,7 @@ impl LimitedString {
         if let Some(limit) = self.max_length {
             let remaining_length = limit - self.length();
             self.content
-                .push_str(&utils::take_graphemes(s, remaining_length));
```
Comment (Minoru) [inline rust/libnewsboat/src/fmtstrformatter/limited_string.rs]: Same as with `utils::graphemes_count`: is it used elsewhere? Can it be removed now?

**Comment by dennisschagt** [comment]
All remarks have been taken care of.

@Minoru: Thanks for the quick review!

File: rust/libnewsboat/src/utils.rs [hunk 5]
```diff
@@ -634,23 +634,6 @@ pub fn mkdir_parents<R: AsRef<Path>>(p: &R, mode: u32) -> io::Result<()> {
...
-/// use libnewsboat::utils::take_graphemes;
-///
-/// let input = "Привет!";
-/// assert_eq!(take_graphemes(input, 1), "П");
-/// assert_eq!(take_graphemes(input, 4), "Прив");
-/// assert_eq!(take_graphemes(input, 6), "Привет");
-/// assert_eq!(take_graphemes(input, 20), input);
-/// ```
-pub fn take_graphemes(input: &str, n: usize) -> String {
-    UnicodeSegmentation::graphemes(input, true)
```
Comment (Minoru) [inline rust/libnewsboat/src/utils.rs]: [rustc warns](https://cirrus-ci.com/task/5940998089998336?command=build#L338) that this was the last use of `UnicodeSegmentation`, and a quick `git grep` shows that we don't need `unicode_segmentation` crate anymore, so it can be removed from rust/libnewsboat/Cargo.toml now. (I should've probably ask about all of this is my previous comment, sorry about that)

Comment (dennisschagt) [reply rust/libnewsboat/src/utils.rs]: No problem, just fixed it.
I just find it hard to see the relevant warnings given the amount of `deprecated trim_end_matches` warnings.

Comment (Minoru) [reply rust/libnewsboat/src/utils.rs]: 299c311 removes the import, but not the crate?

Comment (Minoru) [reply rust/libnewsboat/src/utils.rs]: > I just find it hard to see the relevant warnings given the amount of deprecated trim_end_matches warnings.

Yeah, everybody is tired of them by now, so after 2.19 release we'll switch to a more aggressive schedule regarding Rust (so we don't have to look at warnings for long), and I'll probably enable `-Werror` like we do for C++.

Comment (dennisschagt) [reply rust/libnewsboat/src/utils.rs]: Apparently the crate uses a dash where the `extern crate` uses an underscore.
That's why my `git grep unicode_segmentation` didn't find the crate usage in the Cargo.toml file (and I somehow overlooked the actual filename you mentioned, sorry about that).

**Comment by Minoru** [comment]
Okay, now that's *done* done. Thanks, @dennisschagt! I'll merge when CI finishes.
