### PR TITLE
Fix "no title on empty feed" issue

### LINKED ISSUE #732: Feed title is ignored if no entries are to be found
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
```
> newsboat -v
newsboat 2.18.0 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2019 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2019 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json

newsboat 2.18.0
System: Linux 5.4.14-gentoo (x86_64)
Compiler: g++ 9.2.0
ncurses: ncurses 6.1.20190609 (compiled with 6.1)
libcurl: libcurl/7.66.0 OpenSSL/1.1.1d zlib/1.2.11 (compiled with 7.66.0)
SQLite: 3.30.1 (compiled with 3.30.1)
libxml2: compiled with 2.9.9
Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):
```

I have a tool monitoring prices and generating an Atom feed with entries for price cuts (https://git.sr.ht/~q3cpma/haggle) that always start with an empty feed.

If you add such a (local) feed containing:
```
<feed xmlns="http://www.w3.org/2005/Atom">
  <title>Haggle - price monitoring</title>
  <id>file:///home/q3cpma/Programming/haggle/news.xml</id>
  <updated>2020-01-26T09:28:10Z</updated>
</feed>
```
via `file:///myfeed.xml` in the urls file and refresh, the title isn't picked up until some entries get added.

### PR DESCRIPTION
**Pull request by dennisschagt**
Fixes #732.

The issue was caused by not updating (replacing) the feed if the number of articles was 0.

Query feeds are explicitly not updated because that would result in unread/total counts to reset to 0 in the feed overview (on `OP_RELOAD`->`Reloader::reload()`).
A different solution to that might be to make the reload function call `View::prepare_query_feed()` [1] for single feeds (make it similar to `Reloader::reload_all` [2]).

[1] https://github.com/newsboat/newsboat/blob/1574cf6c2f615339c4be3030b81a99173daa3e7e/src/view.cpp#L999-L1012

[2] https://github.com/newsboat/newsboat/blob/1574cf6c2f615339c4be3030b81a99173daa3e7e/src/reloader.cpp#L176-L181

### CODE REVIEW

File: src/reloader.cpp [hunk 1]
```diff
@@ -82,10 +82,11 @@ void Reloader::reload(unsigned int pos,
 		try {
 			oldfeed->set_status(DlStatus::DURING_DOWNLOAD);
 			std::shared_ptr<RssFeed> newfeed = parser.parse();
-			if (newfeed->total_item_count() > 0) {
+			if (!newfeed->is_query_feed()) {
```
Comment (Minoru) [inline src/reloader.cpp]: I'd move this wa-a-ay higher, right after the definition of `oldfeed`—this method doesn't know how to populate query feeds, so it makes sense to skip them as early as possible. `reload_all` will take care of populating them at the end.

A comment to that effect would be nice as well.

Comment (dennisschagt) [reply src/reloader.cpp]: Good idea, done.

Also added the comment.
If you have a better suggestion for [the comment](https://github.com/newsboat/newsboat/pull/746/commits/46547a749b1a05bfcc1a5e1d93bc93c01e7319d3#diff-82d82421c3bacb97d6028178bb3e5df3R65-R66), I'm definitely open to that

Comment (Minoru) [reply src/reloader.cpp]: Thanks! The comment looks good to me. I'll merge once the builds finish.

**Comment by Minoru** [comment]
Merged. Thanks, @dennisschagt!
