### PR TITLE
Highlight search phrase case insensitively

### LINKED ISSUE #2998: Highlighting in HelpFormAction is case sensitive
**Newsboat version**: Current master (9189eb858305672fbbf6aa96193d2520853a6a13)

Steps to reproduce the issue:

1. Open help window (press `?`)

2. Search for "open" (`/open<ENTER>`)

3. Notice that lines containing "open" and "Open" show up (as expected) but only the "open" occurrences with the same capitalization are highlighted

**Other info you think is relevant**:

Image

### PR DESCRIPTION
**Pull request by juntuu**
I think case-insensitive regex search & replace is suitable for this.

There could still be some discrepancy between the case matching of this and `strcasestr`, which is used as the precondition check.

The added function is quite specific. It might also be beneficial to construct the regex once outside the `apply_highlights` lambda, but don't know if it's worth the bridging effort.

Fixes #2998

### CODE REVIEW

**Comment by juntuu** [comment]
Seems like there are more issues with stfl quoting. Searching for `<` or `>` misbehaves, as does highlighting next to those characters.

Not sure if broken in these changes, or somewhere else. I'll investigate later, setting as a draft for now.

**Comment by juntuu** [comment]
I changed the approach a bit, and made the highlighting a method on StflRichText. To me this feels nicer for the use case.

File: src/helpformaction.cpp [hunk 1]
```diff
@@ -166,11 +160,11 @@ void HelpFormAction::prepare()
...
 				const std::string description = macro.second.description;
 
-				// "macro-prefix" is not translated because it refers to an operation name
-				std::string line = strprintf::fmt("<macro-prefix>%s  %s", key, description);
-				line = utils::quote_for_stfl(line);
-				line = apply_highlights(line);
-				listfmt.add_line(StflRichText::from_quoted(line));
+				if (should_be_visible({ macro.first, "", description, "", 0 })) {
+					// "macro-prefix" is not translated because it refers to an operation name
+					std::string line = strprintf::fmt("<macro-prefix>%s  %s", key, description);
```
Comment (juntuu) [inline src/helpformaction.cpp:165]: There is still a minor mismatch here. The `<macro-prefix>` is not part of the search, but it is part of the highlighting.

I suppose it is fine, though.

**Review by dennisschagt — APPROVED** [review]
Nice, LGTM
