### PR TITLE
Use description as title when URL ends with digits

### LINKED ISSUE #2530: Mastodon feeds show numeric titles
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

Newsboat r2.32-126-g1d04

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
datetime-format "%b %d %Y"
```

Steps to reproduce the issue:

1. Add a feed for a Mastodon user, e.g.

```
https://fosstodon.org/@vilcans.rss
```

2. Open newsboat. Refresh and open the feed.

3. Note that the title of each toot is an 18 digit number instead of something meaningful.

**Other info you think is relevant**:

Apparently Mastodon items don't have `<title>` tags, so Newsboat creates a title from the item's URL. But for Mastodon feeds, the URL ends with just a numeric id, e.g. https://fosstodon.org/@vilcans/110972142261766590 where the title would be "110972142261766590". It would be more useful to have the description (the toot content) as the title instead.

In the current implementation, `RssParser::set_item_title` calls `utils::make_title` which calls the Rust function `make_title` that extracts the relevant part of the URL that can be used as the title. For a Mastodon feed, this will be a number.

Suggestion: Change the heuristics of `make_title` so that it does not generate a title based on the URL if the title would then only contain decimal digits. And in that case, use the item's description instead.

### PR DESCRIPTION
**Pull request by vilcans**
Showing a numeric identifier as the title is not very useful, and it happens on Mastodon RSS feeds. Use the description instead.

Fixes #2530

### CODE REVIEW

File: rust/libnewsboat/src/utils.rs [hunk 1]
```diff
@@ -551,9 +551,16 @@ pub fn make_title(rs_str: String) -> String {
...
     // Un-escape any percent-encoding, e.g. "It%27s%202017%21" -> "It's
     // 2017!"
-    match unescape_url(result) {
+    let result = match unescape_url(result) {
         None => String::new(),
         Some(f) => f,
+    };
+
+    // If it contains only digits, assume it's an id, not a proper title
+    if result.as_bytes().iter().all(u8::is_ascii_digit) {
```
Comment (Minoru) [inline rust/libnewsboat/src/utils.rs:560]:
```suggestion
    if result.chars().all(char::is_ascii_digit) {
```

That way, one doesn't have to perform mental gymnastics to figure out that in UTF-8, "all bytes are ASCII digits" is equivalent to "all chars are ASCII digits".

**Comment by Minoru** [comment]
Looks great, thank you very much!

File: rust/libnewsboat/src/utils.rs [hunk 2]
```diff
@@ -551,9 +551,16 @@ pub fn make_title(rs_str: String) -> String {
...
     // Un-escape any percent-encoding, e.g. "It%27s%202017%21" -> "It's
     // 2017!"
-    match unescape_url(result) {
+    let result = match unescape_url(result) {
         None => String::new(),
         Some(f) => f,
+    };
+
+    // If it contains only digits, assume it's an id, not a proper title
+    if result.chars().all(char::is_ascii_digit) {
```
Comment (Minoru) [inline rust/libnewsboat/src/utils.rs:560]:
```suggestion
    if result.chars().all(|c| c.is_ascii_digit()) {
```
