### PR TITLE
Fixes #401: Highlighting bug

### LINKED ISSUE #401: Highlighting the "Link" field messes up colors
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
newsboat 2.14.0
System: Linux 4.20.0-arch1-1-ARCH (x86_64)
Compiler: g++ 8.2.1 20181127
ncurses: ncurses 6.1.20180127 (compiled with 6.1)
libcurl: libcurl/7.63.0 OpenSSL/1.1.1a zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.4) libssh2/1.8.0 nghttp2/1.35.1 (compiled with 7.63.0)
SQLite: 3.26.0 (compiled with 3.26.0)
libxml2: compiled with 2.9.8
Terminal: st (also tried xterm, and inside tmux, with no changes)

**Steps to reproduce the issue:**

1. Empty your config, then add the following lines:
```
highlight article "^L" red
highlight article "http" blue
```

2. Open any article

**Other info you think is relevant**:

To be more specific, highlighting just the first letter "L" of the "Link:" field at the top (more than just the first letter can be included though), with another highlight anywhere in the same line will cause the color of the "L" to be applied to all text after the second highlight, until a third highlight is found. This sounds confusing but the screenshot explains it better.

Here, the second highlight is "archlinux" instead:
screenshot

The colors or attributes used for the highlight don't matter. The same thing happens even when the second highlight is just "default" with no attributes.

### PR DESCRIPTION
**Pull request by zaowen**
Marker extract function, renamed to better indicate new generalfunctionality, rescoped to allow testing.
Highlight now properly reopens tags, rather than always inserting tags at begining of line.

### CODE REVIEW

File: src/regexmanager.cpp [hunk 1]
```diff
@@ -222,18 +223,57 @@ void RegexManager::remove_last_regex(const std::string& location)
...
+	regex_t regex;
+	// Non-zero number or non-angle bracket characters, enclosed in angle brackets
+	const char *regexpat = "<[^<>]+>";
+	std::string close = "</>";
+	std::string tmptag;
+	std::stack<std::string> tagstack;
+	int offset = 0;
+
 	if (str.length() == 0)
 		return "";
```
Comment (Minoru) [inline src/regexmanager.cpp]: Please apply the boyscout rule and put this line in curly braces. Same goes for an `if` below.

File: src/regexmanager.cpp [hunk 2]
```diff
@@ -222,18 +223,57 @@ void RegexManager::remove_last_regex(const std::string& location)
...
+			}
+		} else { //othewise add the tag to the stack
+			tagstack.push(tmptag);
 		}
+		offset += pmatch.rm_eo;
+		err = regexec(&regex, str.c_str() + offset, 1, &pmatch, 0);
 	}
-	return "";
+
+	if(!tagstack.empty()) {
```
Comment (Minoru) [inline src/regexmanager.cpp]: Please put a space after `if`.

File: src/regexmanager.cpp [hunk 3]
```diff
@@ -222,18 +223,57 @@ void RegexManager::remove_last_regex(const std::string& location)
...
+		return tagstack.top();
+	}
+
+		return "";
```
Comment (Minoru) [inline src/regexmanager.cpp]: Please fix the indentation here.

Also, this function leaks memory because `regfree` is never called on `regex`. I understand that the rest of the code here uses C's <regex.h>, but I suggest to rewrite this with C++'s <regex>.

File: src/regexmanager.cpp [hunk 4]
```diff
@@ -246,18 +286,19 @@ void RegexManager::quote_and_highlight(std::string& str,
 		if (!regex) {
 			continue;
 		}
-		std::string initial_marker = extract_initial_marker(str);
+		std::string outer_marker = "";
```
Comment (Minoru) [inline src/regexmanager.cpp]: This variable is only used inside the loop, so please move the declaration there.

File: src/regexmanager.cpp [hunk 5]
```diff
@@ -222,18 +223,57 @@ void RegexManager::remove_last_regex(const std::string& location)
...
+	// Non-zero number or non-angle bracket characters, enclosed in angle brackets
+	const char *regexpat = "<[^<>]+>";
+	std::string close = "</>";
+	std::string tmptag;
+	std::stack<std::string> tagstack;
+	int offset = 0;
+
 	if (str.length() == 0)
 		return "";
+	// Compile regex
```
Comment (Minoru) [inline src/regexmanager.cpp]: Please remove this comment since it doesn't add any new information (`regcomp` is pretty descriptive).

File: src/regexmanager.cpp [hunk 6]
```diff
@@ -222,18 +223,57 @@ void RegexManager::remove_last_regex(const std::string& location)
...
+		tmptag = str.substr( pmatch.rm_so+offset, pmatch.rm_eo-pmatch.rm_so);
+		// If the found tag is after the spot we're looking for
+		if (pmatch.rm_so+offset > index ){
+			if(!tagstack.empty() ) {
+				return tagstack.top();
+			} else {
+				return "";
+			}
+		}
+		// If the found tag is a closeing tag
```
Comment (Minoru) [inline src/regexmanager.cpp]: Please remove this comment, since reader already knows that `close` is a closing tag and `tmptag == close` is descriptive enough.

File: src/regexmanager.cpp [hunk 7]
```diff
@@ -222,18 +223,57 @@ void RegexManager::remove_last_regex(const std::string& location)
...
+		if (tmptag == close) {
+			//If a tag is closed without a partner error out
+			if (tagstack.empty()) {
+				return "";
+			} else {
+				//otherwise pop it off the stack
```
Comment (Minoru) [inline src/regexmanager.cpp]: Please remove this comment and the one that follows, since they both just repeat what the code says already.

File: src/regexmanager.cpp [hunk 8]
```diff
@@ -222,18 +223,57 @@ void RegexManager::remove_last_regex(const std::string& location)
...
 }
 
-std::string RegexManager::extract_initial_marker(const std::string& str)
+std::string RegexManager::extract_outer_marker(const std::string str, const int index)
 {
+	regmatch_t pmatch;
+	regex_t regex;
+	// Non-zero number or non-angle bracket characters, enclosed in angle brackets
+	const char *regexpat = "<[^<>]+>";
+	std::string close = "</>";
```
[the remark this answers is not in the document]
Comment (zaowen) [reply src/regexmanager.cpp]: Good one, thanks.

File: src/regexmanager.cpp [hunk 9]
```diff
@@ -222,18 +223,57 @@ void RegexManager::remove_last_regex(const std::string& location)
 	regexes.erase(it);
 }
 
-std::string RegexManager::extract_initial_marker(const std::string& str)
+std::string RegexManager::extract_outer_marker(const std::string str, const int index)
 {
+	regmatch_t pmatch;
```
[the remark this answers is not in the document]
Comment (zaowen) [reply src/regexmanager.cpp]: Good idea, thank you

File: src/regexmanager.cpp [hunk 10]
```diff
@@ -222,18 +223,57 @@ void RegexManager::remove_last_regex(const std::string& location)
...
+	regex_t regex;
+	// Non-zero number or non-angle bracket characters, enclosed in angle brackets
```
[the remark this answers is not in the document]
Comment (zaowen) [reply src/regexmanager.cpp]: _of_ Thank you.

File: test/regexmanager.cpp [hunk 11]
```diff
@@ -144,3 +144,75 @@ TEST_CASE("RegexManager does not hang on regexes that match empty strings", "[Re
...
+
+	SECTION("Begining of line match second")
+	{
+		rxman.handle_action("highlight", {"article", "brown", "blue"});
+		rxman.handle_action("highlight", {"article", "the", "red"});
+		rxman.quote_and_highlight(input, "article");
+		REQUIRE(input == start2output);
+	}
+
+	SECTION("testing empty line")
```
[the remark this answers is not in the document]
Comment (zaowen) [reply test/regexmanager.cpp]: Got it, Thanks.

File: src/regexmanager.cpp (hunk 1 above)
Comment (zaowen) [reply src/regexmanager.cpp]: Take only photographs, leave only curly braces. Done, Thanks

File: src/regexmanager.cpp (hunk 2 above)
Comment (zaowen) [reply src/regexmanager.cpp]: Thank you.

File: src/regexmanager.cpp (hunk 4 above)
Comment (zaowen) [reply src/regexmanager.cpp]: Thank you.

File: src/regexmanager.cpp (hunk 5 above)
Comment (zaowen) [reply src/regexmanager.cpp]: Thanks

File: test/regexmanager.cpp [hunk 12]
```diff
@@ -144,3 +144,75 @@ TEST_CASE("RegexManager does not hang on regexes that match empty strings", "[Re
 		REQUIRE(input == compare);
 	}
 }
+
+TEST_CASE("RegexManager does insert extra garbage", "[RegexManager]")
```
[the remark this answers is not in the document]
Comment (zaowen) [reply test/regexmanager.cpp]: It was supposed to say _doesn't_, but your description is much better. Thanks.

File: test/regexmanager.cpp [hunk 13]
```diff
@@ -144,3 +144,75 @@ TEST_CASE("RegexManager does not hang on regexes that match empty strings", "[Re
...
+{
+	RegexManager rxman;
+	std::string input =  "The quick brown fox jumps over the lazy dog";
+	std::string start1output = "<0>The</> quick <1>brown</> fox jumps over <0>the</> lazy dog";
```
[the remark this answers is not in the document]
Comment (zaowen) [reply test/regexmanager.cpp]: Done, and thanks.

**Comment by zaowen** [comment]
Due to the change from <regex.h> to <regex>. Many changes have occured within `extract_outer_marker()`. The functionality should be the same, minus the memory leak.

**Comment by Minoru** [comment]
Sorry I'm neglecting this PR for so long. I'll do it first thing in the evening tomorrow, promise! (That's like 19 hours from now).

**Comment by zaowen** [comment]
@Minoru take your time.

File: src/regexmanager.cpp (hunk 2 above)
Comment (Minoru) [reply src/regexmanager.cpp]: Um, this wasn't addressed, but it's not important enough to go through another review cycle. I'll just put that space there myself ;)

**Comment by Minoru** [comment]
Great, thank you very much @zaowen!
