### PR TITLE
Preserve line breaks in tags inside <pre>

### LINKED ISSUE #2003: New lines in tags inside <pre> do not show up
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
```
Newsboat 2.26.0 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2021 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2021 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles:
- JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
- optional-lite library, licensed under the Boost Software License: https://github.com/martinmoene/optional-lite
- expected-lite library, licensed under the Boost Software License: https://github.com/martinmoene/expected-lite

Newsboat 2.26.0
System: Linux 5.15.27-1-lts (x86_64)
Compiler: g++ 11.1.0
ncurses: ncurses 6.3.20211021 (compiled with 6.3)
libcurl: libcurl/7.82.0 OpenSSL/1.1.1m zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.47.0 (compiled with 7.80.0)
SQLite: 3.38.0 (compiled with 3.37.0)
libxml2: compiled with 2.9.12
```

**Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):**

```
history-limit 0
browser "echo -n %u | copyclip"

bind-key c open-in-browser article
bind-key m toggle-article-read
#ignore-article "*" "tags # \"youtube\" and (title # \"#shorts\" or content # \"#shorts\" or title # \"#Shorts\" or content # \"#Shorts\")"
ignore-article "*" "title # \"#shorts\" or content # \"#shorts\" or title # \"#Shorts\" or content # \"#Shorts\" or title # \"#SHORTS\" or content # \"#SHORTS\""
ignore-mode "display"
```

**Steps to reproduce the issue:**

1. Copy the following feed into a file:
```
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
    <channel>
        <title>example</title>

        <item>
            <title>dying example</title>
            <guid>0</guid>
            <pubDate>Tue, 15 Mar 2022 00:00:00 +0000</pubDate>
            <description>
&lt;pre&gt;&lt;code&gt;&lt;span&gt;// comment 0
&lt;/span&gt;&lt;span&gt;// comment 1
&lt;/span&gt;&lt;/code&gt;&lt;/pre&gt;</description>
        </item>
        <item>
            <title>another dying example</title>
            <guid>0.5</guid>
            <pubDate>Tue, 14 Mar 2022 00:00:00 +0000</pubDate>
            <description>
&lt;pre&gt;&lt;code&gt;&lt;somethinghere&gt;// comment 0
&lt;/somethinghere&gt;&lt;somethinghere&gt;// comment 1
&lt;/somethinghere&gt;&lt;/code&gt;&lt;/pre&gt;</description>
        </item>
        <item>
            <title>not dying example</title>
            <guid>1</guid>
            <pubDate>Tue, 13 Mar 2022 00:00:00 +0000</pubDate>
            <description>
&lt;pre&gt;&lt;code&gt;&lt;span&gt;// comment 0&lt;/span&gt;
&lt;span&gt;// comment 1&lt;/span&gt;&lt;/code&gt;&lt;/pre&gt;</description>
        </item>
    </channel>
</rss>
```

2. Load the feed into newsboat and open the example

### PR DESCRIPTION
**Pull request by the-blank-x**
FIxes #2003

### CODE REVIEW

File: test/htmlrenderer.cpp [hunk 1]
```diff
@@ -474,6 +474,26 @@ TEST_CASE("tags still work inside <pre>", "[HtmlRenderer]")
 	REQUIRE(links.size() == 0);
 }
 
+TEST_CASE("line breaks are preserved in tags inside <pre>", "[HtmlRenderer]")
+{
+	HtmlRenderer r;
+
+	const std::string input =
+		"<pre><span>very cool\n\n\n"
```
Comment (Minoru) [inline test/htmlrenderer.cpp:482]: Let's also check that the leading whitespace is ignored:

```suggestion
		"<pre>
		<span>very cool\n\n\n"
```

**Comment by Minoru** [comment]
Thank you, both for the report and for this fix! The code looks good to me, but in my testing with Firefox 91 and Chromium 99 I found that only a single newline is ignored at the start and the end of the block. Please see the attached HTML page for a demonstration; just open it in a browser of your choice: [index.html.gz](https://github.com/newsboat/newsboat/files/8289804/index.html.gz) (you'll have to unzip it because GitHub won't let me attach a raw HTML document). I think handling a single newline would actually simplify the code.
