### PR TITLE
Only add default keys into keymap for relevant context

### LINKED ISSUE #840: KeyMap: Entries in `opdescs` overwrite for all contexts
**Newsboat version**: `commit 307beab720bfc8456d4516fa5b518f7177da6d89 (HEAD -> master)`

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config): Empty

Steps to reproduce the issue:

1. Observe the following keybinding [in src/keymap.cpp](https://github.com/newsboat/newsboat/blob/307beab720bfc8456d4516fa5b518f7177da6d89/src/keymap.cpp#L366-L372) which binds the "g"-key to `sort` in the feedlist and articlelist:
    `{ OP_SORT, "sort", "g", _("Sort current list"), KM_FEEDLIST | KM_ARTICLELIST },`

2. Add a new line below that binding which binds the "g"-key to some other action for a different context (like the article view):
    `{ OP_NEXT, "next", "g", _("Go to next article"), KM_ARTICLE },`

3. Observe that the new key binding overwrites the old binding in all contexts (even though it only specified `KM_ARTICLE`).

**Other info you think is relevant**:
Caused by an incorrect implementation [in the KeyMap constructor](https://github.com/newsboat/newsboat/blob/307beab720bfc8456d4516fa5b518f7177da6d89/src/keymap.cpp#L478-L495).
The [if statement](https://github.com/newsboat/newsboat/blob/307beab720bfc8456d4516fa5b518f7177da6d89/src/keymap.cpp#L489) does not take the context into account so it either adds a binding for all contexts or it does not add it at all.

### PR DESCRIPTION
**Pull request by dennisschagt**
Fixes #840 

I'm aware there are already tests for KeyMap but I don't see a good way to test this change without refactoring (at least a little bit).
I did do some manual testing which worked as expected.

Following are screenshots showing the resulting keymap (similar to https://github.com/newsboat/newsboat/issues/840#issuecomment-604489151 but now a lot more sparse).

#### Newsboat
Screenshot_20200327_003640

#### Podboat
Screenshot_20200327_003647

### CODE REVIEW

File: src/keymap.cpp [hunk 1]
```diff
@@ -482,13 +482,17 @@ KeyMap::KeyMap(unsigned flags)
...
 	LOG(Level::DEBUG, "KeyMap::KeyMap: flags = %x", flags);
-	for (unsigned int j = 1; contexts[j] != nullptr; j++) {
-		std::string ctx(contexts[j]);
-		for (int i = 0; opdescs[i].op != OP_NIL; ++i) {
-			if (opdescs[i].flags &
-				(flags | KM_INTERNAL | KM_SYSKEYS)) {
-				keymap_[ctx][opdescs[i].default_key] =
-					opdescs[i].op;
+	for (int i = 0; opdescs[i].op != OP_NIL; ++i) {
+		OpDesc op_desc = opdescs[i];
```
Comment (Minoru) [inline src/keymap.cpp]: `op_desc`, `context`, and `context_flag` can all be marked `const`.

Comment (dennisschagt) [reply src/keymap.cpp]: Done, thanks
