### PR TITLE
HtmlRenderer: do not look inside <script>s

### LINKED ISSUE #1300: double free or corruption (out) core dump on large sized js enabled site.
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: newsboat r2.21 

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
save-path "/home/rmday/Documents/saved-articles/"
#urls-source "ocnews"
#ocnews-url "https://cloud.disroot.org/"
#ocnews-login "presgas"
#ocnews-flag-star "s"
max-items 250
article-sort-order date-desc
auto-reload yes
reload-time 120
reload-threads 8


# Dark solarized color scheme for newsbeuter, based on
# Ethan Schoonover's Solarized.
#
# In order to use this color scheme, you must first configure
# your terminal emulator to use the Solarized palette.
# See <http://ethanschoonover.com/solarized/> for more information.

color background   default   default
color listnormal   default   default
color listnormal_unread   default   default
color listfocus    black     yellow
color listfocus_unread    black     yellow
color info         default   black
color article      default   default

# highlights
highlight article "^(Title):.*$" blue default
highlight article "https?://[^ ]+" red default
highlight article "\\[image\\ [0-9]+\\]" green default

ignore-article "*" "author =~ \"Greyhawk Grognard\""
ignore-article "*" "author =~ \"Timothy S. Brannan\""
ignore-article "*" "author =~ \"James V. West\""
#ignore-article "*" "link =~ MonstersAndManuals"

```

Steps to reproduce the issue:

1. Select article from rss feed with what looks like a large payload (js)

> Nov 22 281.4K  Finders Keepers

2. newsboat crashes 

3. double free or corruption (out)

**Other info you think is relevant**: The rss feed that I did get this from was a planet aggregator (https://campaignwiki.org/rpg/) with rss feed (https://campaignwiki.org/rpg/atom.xml). There have been other large looking articles that have done this, but this is the first I really tried to get info on. The actual article causing the crash is titled "Finders Keepers" and is here:

https://slightadjustments.blogspot.com/2020/08/finders-keepers-in-space.html

Many of the articles are using js for generators and this may well be the issue, but letting "the experts" look this over.

### PR DESCRIPTION
**Pull request by Minoru**
Fixes #1300, where HtmlRenderer bumped into \<ul> tags inside the script, causing it to mis-count the indentation of lists and eventually pop an element off the empty vector.

Reviews are welcome! I'll merge in three days if no issues are raised.

### CODE REVIEW

File: src/htmlrenderer.cpp [hunk 1]
```diff
@@ -761,12 +777,9 @@ void HtmlRenderer::render(std::istream& input,
...
 			case HtmlTag::SCRIPT:
-				// don't render scripts, ignore current line
-				if (inside_script) {
-					inside_script--;
-				}
-				prepare_new_line(curline,
-					tables.size() ? 0 : indent_level);
+				// This line is unreachable, since we handle closing <script>
+				// tags way before this entire `switch`.
+				assert(false);
```
Comment (dennisschagt) [inline src/htmlrenderer.cpp:782]: With correct html input, this is indeed unreachable.

However, if an rss feed contains invalid html (e.g. a closing `</SCRIPT>` tag without an opening `<SCRIPT>` tag), this can still be reached.

**Review by dennisschagt — COMMENTED** [review]
Looks good!

File: src/htmlrenderer.cpp (hunk 1 above)
Comment (Minoru) [reply src/htmlrenderer.cpp:782]: You're right. I'll drop the `assert` then. Thanks!

**Review by dennisschagt — APPROVED** [review]
:+1:

**Comment by Minoru** [comment]
Thank you for the review, @dennisschagt!
