### PR TITLE
fixes #545 by throwing rename failure message

### LINKED ISSUE #545: Notify user if the podcast couldn't be renamed
After downloading the podcast file, Podboat [tries to rename it](https://github.com/newsboat/newsboat/blob/3320e011ae9004519af8b7e6b6b90bf45565a9e1/src/poddlthread.cpp#L120) to remove the ".part" suffix. However, the return value of that call is never checked; if rename failed, the user won't know.

Problem flagged by Coverity Scan.

### PR DESCRIPTION
**Pull request by kartikeya100**
Fixes #545 by showing error message to user when unable to rename podcast.

### CODE REVIEW

File: src/queueloader.cpp [hunk 1]
```diff
@@ -69,6 +69,7 @@ nonstd::optional<QueueLoader::CategorizedDownloads> QueueLoader::categorize_down
 		case DlStatus::ALREADY_DOWNLOADED:
 		case DlStatus::READY:
 		case DlStatus::PLAYED:
+		case DlStatus::RENAME_FAILED:
```
Comment (Minoru) [inline src/queueloader.cpp:72]: Please look through `TEST_CASE`s in test/queueloader.cpp and see if any of them need updating because of this change.

File: src/queueloader.cpp [hunk 2]
```diff
@@ -231,6 +232,7 @@ void QueueLoader::write_queue_file(const CategorizedDownloads& downloads) const
 		case DlStatus::DELETED:
 		case DlStatus::FAILED:
 		case DlStatus::ALREADY_DOWNLOADED:
+		case DlStatus::RENAME_FAILED:
```
Comment (Minoru) [inline src/queueloader.cpp:235]: Please check if test cases need updating now.

File: src/poddlthread.cpp [hunk 3]
```diff
@@ -120,8 +120,11 @@ void PodDlThread::run()
 			LOG(Level::DEBUG,
 				"PodDlThread::run: download complete, deleting "
 				"temporary suffix");
-			rename(filename.c_str(), dl->filename().c_str());
-			dl->set_status(DlStatus::READY);
+			if(rename(filename.c_str(), dl->filename().c_str()) == 0){
+				dl->set_status(DlStatus::READY);
+			}else{
+				dl->set_status(DlStatus::RENAME_FAILED,"Unable to rename downloaded file. Please check if you have sufficient permissions.");
```
Comment (Minoru) [inline src/poddlthread.cpp:126]: `rename()` can fail for a number of reasons, see its man page. Instead of a blanket message about permissions, it's better to invoke `strerror` which will return a more detailed message.

**Review by Minoru — CHANGES_REQUESTED** [review]
Looks pretty good! Please see my comments below, and also the failed CI job.

File: src/queueloader.cpp (hunk 1 above)
Comment (kartikeya100) [reply src/queueloader.cpp:72]: Done

File: src/queueloader.cpp (hunk 2 above)
Comment (kartikeya100) [reply src/queueloader.cpp:235]: Done

File: src/poddlthread.cpp (hunk 3 above)
Comment (kartikeya100) [reply src/poddlthread.cpp]: Done

**Review by Minoru — CHANGES_REQUESTED** [review]
Almost there! There's a test called "reload() appends downloads from the array to the queue file", it'd be nice to ensure that downloads that have `RENAME_FAILED` status are written to the queue the same way as `QUEUED` downloads are.

**Review by Minoru — APPROVED** [review]
Thanks a lot @kartikeya100!
