### PR TITLE
Don't tolerate invalid utf-8 in utils::get_command_output() input argument

### LINKED ISSUE #801: utils::get_command_output shouldn't tolerate invalid UTF-8 in arguments
While reviewing #799 I noticed that `utils::get_command_output()` uses `str::to_string_lossy()` to convert a shell command from `str` to `String`. This is mildly dangerous, since "lossy" conversion means any invalid UTF-8 will be replaced by U+FFFD. In other words, Newsboat might run a totally different command from the one specified.

Other similar functions, `utils::run_program()` and `utils::run_command()`, panic on invalid UTF-8 which, while suboptimal, is still better than running the wrong command.

`utils::get_command_output()` should panic on invalid UTF-8.

### PR DESCRIPTION
**Pull request by dennisschagt**
Fixes #801.

I looks like our testing framework (Catch2) does not allow testing for SIGABRT.

Manual testing showed that this works as expected,
using line `REQUIRE(utils::get_command_output("echo -e \"test:\xff\"") == "expecting a test FAIL");`:
image

### CODE REVIEW

File: rust/libnewsboat-ffi/src/utils.rs [hunk 1]
```diff
@@ -515,7 +515,7 @@ pub unsafe extern "C" fn rs_is_valid_podcast_type(mimetype: *const c_char) -> bo
 pub unsafe extern "C" fn rs_get_command_output(input: *const c_char) -> *mut c_char {
     abort_on_panic(|| {
         let rs_input = CStr::from_ptr(input);
-        let rs_input = rs_input.to_string_lossy();
+        let rs_input = rs_input.to_str().expect("input contained invalid UTF-8");
```
Comment (Minoru) [inline rust/libnewsboat-ffi/src/utils.rs]: We always add a comment explaining why `unwrap()` and `expect()` won't panic. Even though this `expect()` says what's wrong with the input, it doesn't explain why you think it won't happen. A lot of these comments are look-alikes; feel free to steal from `rs_run_command()` below.

Comment (dennisschagt) [reply rust/libnewsboat-ffi/src/utils.rs]: I've added a notice telling `This won't panic because all strings in Newsboat are in UTF-8` but I now found a way to still get it to panic.

Putting the following in a `urls` file:
```
https://newsboat.org/news.atom
exec:invalid�
```

created by putting the following in `urls.xxd` and running `xxd -r urls.xxd > urls` (0xff near the end is invalid):
```
00000000: 6874 7470 733a 2f2f 6e65 7773 626f 6174  https://newsboat
00000010: 2e6f 7267 2f6e 6577 732e 6174 6f6d 0a65  .org/news.atom.e
00000020: 7865 633a 696e 7661 6c69 64ff 0a         xec:invalid..
```

A Rust panic now happens when reloading the `exec:` feed.

Comment (dennisschagt) [reply rust/libnewsboat-ffi/src/utils.rs]: 1. Is it useful if I open a separate bug for invalid characters in `urls` file? (similar to #723 but specific to the urls file)

2. Is it useful to delay merging this PR until the above issue is fixed?

Comment (Minoru) [reply rust/libnewsboat-ffi/src/utils.rs]: @dennisschagt, yes to both questions. Can you file the issue, please?

Comment (dennisschagt) [reply rust/libnewsboat-ffi/src/utils.rs]: Sure, done, see #844

**Comment by dennisschagt** [comment]
This PR should not be merged unless issue #844 is resolved.

**Comment by dennisschagt** [comment]
Merging this PR without further review as I only rebased onto master and squashed the commits together.
