### PR TITLE
Source $TMPDIR variable if it exists

### LINKED ISSUE #250: Allow temporary directory to be modified
**Newsboat version (copy from `newsboat -v`)**: 2.12.0

Steps to reproduce the issue:

1. Edit the config file to point to an external pager (any one will do).

2. Use software like [firejail](https://github.com/netblue30/firejail) or systemd to prevent the pager from accessing `/tmp/`. However, _do_ allow access to a subdirectory - for example, since I have `pam_tmpdir` enabled, I give my pager access to `/tmp/user/1000`.

3. Note that `newsboat` doesn't pick up on the `$TMPDIR`, `$TMP`, `$TEMPDIR`, or `$TEMP` variables, which should be set to a directory that your pager _can_ access (`/tmp/user/1000/` in my case).

4. The pager is unable to display the file.

**Other info you think is relevant**:

Maybe I missed something, but it seems that I cannot customize the temporary directory location, which would fix this issue.

### PR DESCRIPTION
**Pull request by chiraag-nataraj**
Would fix #250.

### CODE REVIEW

File: src/controller.cpp [hunk 1]
```diff
@@ -1408,7 +1408,13 @@ int controller::execute_commands(const std::vector<std::string>& cmds)
 std::string controller::write_temporary_item(std::shared_ptr<rss_item> item)
 {
 	char filename[_POSIX_PATH_MAX];
-	snprintf(filename, sizeof(filename), "/tmp/newsboat-article.XXXXXX");
+	char *tmpdir = getenv("TMPDIR");
+	if (tmpdir != NULL) {
```
Comment (Minoru) [inline src/controller.cpp]: Please use `nullptr`, which is type-safe.

File: src/controller.cpp [hunk 2]
```diff
@@ -1408,7 +1408,13 @@ int controller::execute_commands(const std::vector<std::string>& cmds)
...
+	  snprintf(filename, sizeof(filename), "%s/newsboat-article.XXXXXX", tmpdir);
+	}
```
Comment (Minoru) [inline src/controller.cpp]: Please put `else` on the same line as closing and opening brackets: `} else {`.

**Comment by Minoru** [comment]
Cool, thank you very much, @chiraag-nataraj!
