### PR TITLE
Don't mark as read when browser fails

### LINKED ISSUE #570: Do not mark as read on non-zero return code
Occasionally, I attempt to watch a youtube video in newsboat (with mpv set as my browser) and mpv fails to open the video for some reason or another.

It would be nice for newsboat to not mark that item as read in my feed if I'm not actually able to "read" it.

### PR DESCRIPTION
**Pull request by mjsir911**
closes #570

One question: is it alright to break early in this switch, specifically before a `invalidate(itempos)`? Not exactly sure what this is doing..

### CODE REVIEW

File: src/itemlistformaction.cpp [hunk 1]
```diff
@@ -131,12 +131,13 @@ void ItemListFormAction::process_operation(Operation op,
 			itemposname);
 		if (itemposname.length() > 0 && visible_items.size() != 0) {
 			if (itempos < visible_items.size()) {
+				if (v->open_in_browser(visible_items[itempos].first->link())) {
+					break;
```
Comment (Minoru) [inline src/itemlistformaction.cpp]: From a user's perspective, it'd be nice if this showed an error as well; ideally including browser's exit code. Otherwise user might be left with a feeling that their keypress was not processed at all. (The error messages can be shown with `v->show_error(_("Message here"))`).

**Comment by tsipinakis** [comment]
Thanks for taking the time to implement this!

This would also be good to have for `OP_OPENALLUNREADINBROWSER_AND_MARK`, both to keep it consistent and as a fail-safe in case one of the items fails to open.

Given you've already done most of the work this should be trivial to implement.

**Comment by mjsir911** [comment]
I'm having trouble with invalidation, since currently at the end of `OP_OPENALLUNREADINBROWSER_AND_MARK` `invalidate_all()` is called, but presumably if execution halts halfway through, only the successfully viewed items should be invalidated.

**Comment by tsipinakis** [comment]
`invalidate_everything()` is the safe choice, if an item didn't get updated it'll just be redrawn as-is. Even in the current code not all items will be opened (i.e. only unread items, and only up to `max-browser-tabs` each time), yet we still invalidate everything and don't bother to invalidate each one individually.

So don't worry about this part, leaving it as-is will work.

**Comment by mjsir911** [comment]
@Minoru, give me a bit of time to write some tests for this new feature

**Comment by Minoru** [comment]
Oh cool, I forgot we have tests for ItemListFormAction ._. Sure I'll wait :)

**Comment by mjsir911** [comment]
@Minoru good to go!

File: test/itemlistformaction.cpp [hunk 2]
```diff
@@ -133,6 +133,40 @@ TEST_CASE(
 	REQUIRE(feed->unread_item_count() == 0);
 }
 
+TEST_CASE(
+	"OP_OPENBROWSER_AND_MARK does not mark read when browser fails",
+	"[ItemListFormAction]")
+{
+	Controller c;
+	newsboat::View v(&c);
+	TestHelpers::TempFile browserfile;
```
Comment (Minoru) [inline test/itemlistformaction.cpp]: You can remove this object since the "mock browser" (i.e. `false %u`) doesn't write anything there.

File: test/itemlistformaction.cpp [hunk 3]
```diff
@@ -133,6 +133,40 @@ TEST_CASE(
...
+
+	std::string test_url = "http://test_url";
```
Comment (Minoru) [inline test/itemlistformaction.cpp]: It'd be nice to mark this `const` to indicate that the test doesn't change this variable.

File: test/itemlistformaction.cpp [hunk 4]
```diff
@@ -133,6 +133,40 @@ TEST_CASE(
...
+	std::string line;
```
Comment (Minoru) [inline test/itemlistformaction.cpp]: This can be removed as well, for the same reason as `browserfile` above.

Comment (Minoru) [reply test/itemlistformaction.cpp]: @mjsir911, you marked this comment as resolved, but the variable is still there?

**Comment by Minoru** [comment]
Thank you!
