### PR TITLE
Fix padding in conditional branch

### LINKED ISSUE #2645: Format string '%>[char]' not working as intended when placed within conditionals
When including `%>[char]` within a conditional block `%?[char]?[format1]&[format 2]?`, 
you do not get the expected behavior. For example,
using my articlelist-format, `%D   %?T?%-63t%> %T&%t?`, when i open a
query feed composed of multiple feeds, the `%T` does not show up as it
should. Instead, the right of the screen is filled with spaces.

However, if instead remove the conditional block and use `%D   %-63t%> %T`, then it works as intended.

This smells like a bug

**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
Newsboat r2.33-dirty - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2023 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2023 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles:
- JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
- optional-lite library, licensed under the Boost Software License: https://github.com/martinmoene/optional-lite
- expected-lite library, licensed under the Boost Software License: https://github.com/martinmoene/expected-lite

Newsboat r2.33-dirty
System: Linux 6.6.8-arch1-1 (x86_64)
Compiler: g++ 13.2.1 20230801
ncurses: ncurses 6.4.20230520 (compiled with 6.4)
libcurl: libcurl/8.5.0 OpenSSL/3.2.0 zlib/1.3 brotli/1.1.0 zstd/1.5.5 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.11.0 nghttp2/1.58.0 (compiled with 8.2.1)
SQLite: 3.44.2 (compiled with 3.42.0)
libxml2: compiled with 2.11.5

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
# general
auto-reload yes
bookmark-autopilot yes
bookmark-interactive no
browser "browser openTab: %u"
confirm-mark-all-feeds-read no
confirm-mark-feed-read no
external-url-viewer "/ckc/bin/urlview"
feed-sort-order title
history-limit 10000
ignore-mode download
pager "feeder pager: %f"
prepopulate-query-feeds no
reload-threads 4
reload-time 15
show-keymap-hint no
show-read-feeds no
show-title-bar yes
suppress-first-reload yes
swap-title-and-hints no
wrap-scroll yes
toggleitemread-jumps-to-next-unread  no

# colors
color background        black color15
color listnormal        black color15
color listfocus         black color7
color listnormal_unread black color15 bold
color listfocus_unread  black color7  bold
color info              black color6
color article           black color15

# formats
datetime-format "%Y-%m-%d"
articlelist-title-format "%T"
articlelist-format "%D   %?T?%-63t%> %T&%t?"

feedlist-title-format "Feeder"
feedlist-format "%t"
searchresult-title-format "%N %V - Search results (%u unread, %t total)%?F? matching filter `%F'&?"

# keybinds
bind-key k down
bind-key l up
bind-key ENTER open
bind-key SPACE toggle-article-read
bind-key ^K pagedown
bind-key ^L pageup 
bind-key g home
bind-key ^G end
bind-key ^A mark-feed-read
bind-key r toggle-show-read-feeds 
bind-key ^R reload-all
bind-key R  reload
bind-key o open-in-browser articlelist
bind-key / open-search help
bind-key s sort
unbind-key q feedlist
bind-key ^. reload-urls

## feedlist
bind-key SPACE mark-feed-read feedlist
bind-key ; open feedlist
bind-key j prev-dialog feedlist

## articlelist
bind-key h quit articlelist
bind-key j prev-feed articlelist
bind-key ; next-feed articlelist
bind-key d delete-article articlelist

## internal pager
bind-key ; next article
bind-key j prev article

## macros
macro s set browser "signal %u &" ; open-in-browser ; set browser "browser openTab: %u"
macro y set browser "clipboard set: %u" ; open-in-browser ; set browser "browser openTab: %u"
macro p set browser "feeder setPager: internal" ; open-in-browser-noninteractively ; open ; set browser "feeder setPager: dispatch" ; open-in-browser-noninteractively ; set browser "browser openTab: %u"

```

Steps to reproduce the issue:

1. Set articlelist-format to something like `%D   %?T?%-63t%> %T&%t?`

2. Open a feed which contains different feeds

3. `%T` will not appear on the right as it should, instead the right of the screen will be filled with ' '

**Other info you think is relevant**:

### PR DESCRIPTION
**Pull request by juntuu**
Each padding will add one of the padding character while the result is built. The left most padding is then expanded only at the end, when we have all the surrounding context formatted.

fixes #2645

I kept the `StringParts` in the same file, and it's only tested through the use in formatting.

### CODE REVIEW

File: rust/libnewsboat/src/fmtstrformatter/mod.rs [hunk 1]
```diff
@@ -58,6 +58,85 @@ pub struct FmtStrFormatter {
...
+        let limit = self.width;
+        let push = |to: &mut LimitedString| {
+            if let Some(remaining) = limit {
+                let remaining = remaining.saturating_sub(to.length());
+                let count = utils::strwidth(content);
+                if remaining >= count {
+                    to.push_str(content);
+                } else {
+                    to.push_str(&utils::substr_with_width(content, remaining));
+                }
```
Comment (Minoru) [inline rust/libnewsboat/src/fmtstrformatter/mod.rs:96]: The calculation of `remaining` seems wrong to me: `self.width` is shared by `self.head` and `self.spaced_tail`, but here we're subtracting just the length of the tail from it to obtain how much space we have.

More importantly, why do we calculate the remaining space at all? Can't we just always `to.push_str(content)` and let `LimitedString` deal with the excess?

**Review by Minoru — COMMENTED** [review]
Thank you very much for this work! Quite intricate code, took a while to grok what's going on. I think I might have found a bug, please see my comment below.

File: rust/libnewsboat/src/fmtstrformatter/mod.rs (hunk 1 above)
Comment (juntuu) [reply rust/libnewsboat/src/fmtstrformatter/mod.rs:96]: This can be an over-estimate of the remaining space, but I don't think it would ever cut the content short. So, not quite correct, but shouldn't change the result.

I took this initially from the `Specifier::Text` case https://github.com/newsboat/newsboat/pull/2655/files#diff-e0721650294fa7f298a66c850cf480042c3cd23f2aa3087f8da1c26a8ff37b30L186. Now that I look this again, it doesn't really make sense. The `LimitedString::push_str()` does the exact same check anyway.

I'll remove this check, as it is now just confusing, bit incorrect and unnecessary.

Comment (Minoru) [reply rust/libnewsboat/src/fmtstrformatter/mod.rs]: You're right, saying it's "wrong" was an exaggeration. Sorry about that.

**Comment by Minoru** [comment]
Thanks!
