### PR TITLE
Specify width when formatting articlelist-title to get "%>-" to work

### LINKED ISSUE #88: String format sequence "%>[char]" doesn't work with articlelist-title-format
Newsboat r2.10.1-110-g7f11

I've got the following lines in my newsboat config:

    feedlist-title-format "%N - feeds %>-"
    articlelist-title-format "%N - %T %>-"
    itemview-title-format "%T %>-"

That [format sequence](https://newsboat.org/releases/2.10.1/docs/newsboat.html#_format_strings) `%>-`, which is supposed to create a line of hyphens to the right edge of the terminal window, doesn't work for `articlelist-title-format`, although it works for the other two. It also appears to not work with (at least) `help-title-format` too.

### PR DESCRIPTION
**Pull request by dennisschagt**
Fixes #88

### CODE REVIEW

File: src/itemlistformaction.cpp [hunk 1]
```diff
@@ -1097,12 +1097,15 @@ void ItemListFormAction::set_head(const std::string& s,
 
 	fmt.register_fmt('U', utils::censor_url(url));
 
+	unsigned int width = utils::to_u(f->get("title:w"));
```
Comment (Minoru) [inline src/itemlistformaction.cpp]: `const`? :P

Comment (dennisschagt) [reply src/itemlistformaction.cpp]: Oops, again :smiley:
