### PR TITLE
Fix filebrowser/dirbrowser title showing ".."

### LINKED ISSUE #731: File browser reports ".." instead of actual directory name
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: f80387f9c4a496258d6839bc472c8a0dc6b9e58f 

Config empty.

Steps to reproduce the issue:

1. open any article;

2. press `s` to save it;

3. in the file browser, press Tab to move from the input field to the list of files and directories. Observe that the title of the dialog say something like "newsboat r2.18-41-gf8038 - Save File - **/home/minoru**";

4. move cursor to ".." and press Enter. This navigates up a filesystem. Notice the dialog title now says "newsboat r2.18-41-gf8038 - Save File - **..**". Expected behaviour is for it to say "newsboat r2.18-41-gf8038 - Save File - **/home**".

### PR DESCRIPTION
**Pull request by dennisschagt**
Fixes #731.

### CODE REVIEW

File: src/dirbrowserformaction.cpp [hunk 1]
```diff
@@ -163,11 +151,27 @@ void DirBrowserFormAction::process_operation(Operation op,
...
+{
+	std::string fileswidth = f->get("files:w");
+	unsigned int width = utils::to_u(fileswidth);
+
+	FmtStrFormatter fmt;
+	fmt.register_fmt('N', PROGRAM_NAME);
+	fmt.register_fmt('V', utils::program_version());
+	fmt.register_fmt('f', working_directory);
+
+	std::string title = fmt.do_format(
```
Comment (Minoru) [inline src/dirbrowserformaction.cpp]: This, along with `fileswidth` and `width` above, could be marked `const`. Ditto in `FileBrowserFormAction`.

**Comment by Minoru** [comment]
Thanks!
